### ISSUE TITLE
ROS 2 Galactic Release Checklist

### ISSUE THREAD

**Issue by cottsay** [ros2/ros2#1001]
Pre-kickoff (during the last stage of previous release)
---
- [x] Choose a ROS boss: @cottsay
- [x] Choose a distribution name: [Galactic Geochelone](https://discourse.ros.org/t/ros-2-g-name-brainstorming)

Kickoff (happens as soon as possible after previous release)
---
- [x] Commission a logo
- [x] Commission a turtlesim icon
- [x] Add to [REP-2000](https://www.ros.org/reps/rep-2000.html) with proposed platforms and minimum requirements, request feedback from community via discourse
  Example from Foxy: ros-infrastructure/rep#217
- [x] Update [ROS 2 documentation](https://github.com/ros2/ros2_documentation/) with expected release date, release notes
  Example from Foxy: ros2/ros2_documentation#445

Mid-development cycle (Alpha, Beta?)
---
- [x] Update Windows and macOS packages
  e.g. brew upgrade, bump Python, bump OpenCV, pinned pip packages, etc...
  Suggest doing this a couple weeks before the beta
  - [x] Bump [REP-2000](https://www.ros.org/reps/rep-2000.html) as well
- [x] Encourage regular package releases after API changes
  This helps keep the debian packaging green and us alert to packaging regressions
- [x] Upgrade all vendored packages to the "latest" (whatever makes sense)
- [x] Do first round of testing

Late development cycle (Divergence/Migration from Rolling)
---
- [x] Add the new distro to rosdistro: ros/rosdistro#29211
- [x] Create a Google Group for the new distro: https://groups.google.com/forum/#!forum/ros2-buildfarm-galactic
- [x] Add new rosdistro as an option to target on [ci.ros2.org](https://ci.ros2.org/): ros2/ci#571
- [x] Release packages to bootstrap the repository
  - [x] Script to take Rolling packages at commit and release into new distro: ros/rosdistro#29221 
    This is a one time deal resulting in two separate distributions with no automated syncs between them
- [x] ~~If this is a new Ubuntu platform:~~
  - [x] ~~Setup new apt repos~~
  - [x] ~~Update CI infrastructure to support new platforms~~
    ~~Example from Foxy: ros2/ci#376 and ros2/ci#414~~
  - [x] ~~Create Docker images for the new platforms in [REP-2000](https://www.ros.org/reps/rep-2000.html) for all targets~~
    ~~Example from Foxy: osrf/multiarch-docker-image-generation#32~~
  - [x] ~~Add newly supported platforms to list of platforms for each Python package (in `stdeb.cfg`)~~
    ~~Use [`ros_release_python`](https://github.com/ros-infrastructure/ros_release_python)~~
    ~~Goal is to make the currently released versions available in the new distros using the `--include` option~~
    ~~In order of dependency:~~
    - [x] ~~catkin_pkg~~
      ~~Example from Foxy: ros-infrastructure/catkin_pkg#271~~
    - [x] ~~rospkg~~
      ~~Example from Foxy: ros-infrastructure/rospkg#184~~
    - [x] ~~rosdistro~~
      ~~Example from Foxy: ros-infrastructure/rosdistro#148~~
    - [x] ~~rosdep~~
      ~~Example from Foxy: ros-infrastructure/rosdep#734~~
    - [x] ~~bloom~~
      ~~Example from Foxy: ros-infrastructure/bloom#558~~
    - [x] ~~rosinstall_generator~~
      ~~Example from Foxy: ros-infrastructure/rosinstall_generator#62~~
    - [x] ~~catkin_tools~~
      ~~Example from Foxy: catkin/catkin_tools#564~~
    - [x] ~~vcstool~~
      ~~Example from Foxy: dirk-thomas/vcstool#112~~
- [x] Enable jobs on [build.ros2.org](http://build.ros2.org/)
  - [x] Add new distribution to the buildfarm configuration: ros2/ros_buildfarm_config#155
    - [x] Copy files from previous distro and do some renaming (separate commits for easy review)
    - [x] Update job priorities (e.g. where they differ between previous two distros)
      Tip: run ./list_priorities.py in root of repo to view a priority list
    - [x] Reduce package count for sync
  - [x] Deploy the jobs after configuration changes are merged
    - [x] On your local machine, install pip dependency jenkinsapi: pip3 install jenkinsapi
    - [x] Generate a buildfarm token for [build.ros2.org](http://build.ros2.org/) (if you don't already have one):
      * Go to [build.ros2.org](http://build.ros2.org/)
      * Login and click on your name (top-right)
      * Under "Configure -> API Token", add a new token
      * Copy the token to add to the file in the next step
      * Create a file ~/.buildfarm/jenkins.ini with the following content (if you don't already have it):
        ```
        [DEFAULT]
        username=admin
        password=changeme
        [http://build.ros2.org]
        username=YOUR_USERNAME
        # Jenkins API token
        password=YOUR_BUILDFARM_TOKEN
        ```
      * Replace `YOUR_USERNAME` with your [build.ros2.org](http://build.ros2.org/) login and replace `YOUR_BUILDFARM_TOKEN` with the token generated in the previous step.
    - [x] Clone the source repo:
    ```
    git clone https://github.com/ros-infrastructure/ros_buildfarm.git
    ```
    - [x] Change to the directory and point `PYTHONPATH` to it:
        ```
        cd ros_buildfarm
        export PYTHONPATH=${PYTHONPATH}:$(pwd)
        ```
    - [x] Run the script without committing to check for errors (replace `ROSDISTRO` as appropriate):
        ```
        ./scripts/generate_all_jobs.py https://raw.githubusercontent.com/ros2/ros_buildfarm_config/ros2/index.yaml --ros-distro-names ROSDISTRO
        ```
    - [x] If there are no errors, re-run with the --commit option (replace `ROSDISTRO` as appropriate):
        ```
        ./scripts/generate_all_jobs.py https://raw.githubusercontent.com/ros2/ros_buildfarm_config/ros2/index.yaml --ros-distro-names ROSDISTRO --commit
        ```
    - [x] Go to [build.ros2.org](http://build.ros2.org/) and run the `Xci_reconfigure-jobs` job for your distro (replace X with the first letter of the distro name, e.g. [Fci_reconfigure-jobs](http://build.ros2.org/job/Fci_reconfigure-jobs/))
- [x] Create matrix for tracking manual testing
  Example from Foxy: https://docs.google.com/spreadsheets/d/1EzDKMGoYopKuGWmzceXTVJ1zWqq1Wxw2jIGsh3CawAQ/edit
    Suggest starting after beta and doing it in rounds (testing/bug fixes for a week, then make new releases, repeat)
- [x] Final release of packages
  - [x] Release any outstanding changes just before the rosdistro freeze
- [x] Create distro branches
  - [x] After rosdistro freeze, ensure each repository has a branch for the new distro
    Suggest creating a workspace with a custom repos file, pruning third-party packages and others that don’t need a new branch. Then run:
    ```
    vcs custom --git --args checkout -b ROSDISTRO
    vcs custom --git --args push origin ROSDISTRO
    ```
  - [x] Create `ros2.repos` files for the new distro, one for the release and one for development
    This command should get you part way there for the release repos file:
    ```
    vcs export --exact-with-tags
    ```
  - [x] Ensure rosdistro points to the new branches: ros/rosdistro#29267
    This script might be useful (no warranty): https://gist.github.com/jacobperron/ba6cc225aefdcee822261b434620766f
  - [x] Update buildfarm CI config to use new distro repos file: ros2/ros_buildfarm_config#157
  - [x] Update ros2_documentation install pages:
    Example from Foxy ros2/ros2_documentation#752
  - [x] Sync release devel branches with branched versions
- [x] Update ROS 2 documentation
  - [x] List install instructions
    Example from Foxy: ros2/ros2_documentation#746
  - [x] List distribution
    Example from Foxy: ros2/ros2_documentation#747
- [x] Update API documentation: ros2/docs.ros2.org#56
   Follow instructions here: https://github.com/ros2/docs.ros2.org/tree/doc_gen
- [x] Add distro to ROS Index: ros-infrastructure/rosindex/pull/264
  - [x] Trigger the Jenkins job: http://build.ros.org/job/doc_rosindex/
- [x] Sync debian packages to main
  - [x] Trigger `Xrel_sync-packages-to-main` on [build.ros2.org](http://build.ros2.org) (replace X with the first letter of the distro name, e.g. [Grel_sync-packages-to-main](http://build.ros2.org/job/Grel_sync-packages-to-main/1/))
- [x] Tag a release on [ros2/ros2](https://github.com/ros2/ros2): ros2/ros2#1147
  - [x] Trigger packaging jobs for macOS and Windows
  - [x] Tag a release and upload the packaging job artifacts: [release-galactic-20210523](https://github.com/ros2/ros2/releases/tag/release-galactic-20210523)
  Use "ci_packaging_*" jobs.
- [x] Update release status on rosdistro: ros/rosdistro#29635
- [x] Announce on Discourse: https://discourse.ros.org/t/ros-2-galactic-geochelone-released

**Comment by cottsay** [comment]
ROS 2 Galactic Geochelone has been released: https://discourse.ros.org/t/ros-2-galactic-geochelone-released
