### ISSUE TITLE
Tracking Issue for RPM patching

### ISSUE THREAD

**Issue by cottsay** [ros2/ros2#1036]
I'm staring the process of adding patches to the release repositories for RPM packages in preparation for merging ros/rosdistro#26262. This is a great opportunity to enumerate everywhere that we need to patch for packaging purposes. Here, I'll link to the reviews for those patches and attempt to categorize the justification for the patches.

Once all of the patches have been shown to work properly on the buildfarm, I'll close this issue.

- [x] `ament_cmake` :boot:
   ros2-gbp/ament_cmake-release#1
- [x] `ament_lint` :red_circle:
   ~~ros2-gbp/ament_lint-release#2~~
   ros2-gbp/ament_lint-release#3
- [x] `ament_package` :red_circle:
   ros2-gbp/ament_package-release#5
- [x] `fastrtps` :question:
   ros2-gbp/fastrtps-release#10
- [x] `google_benchmark_vendor` :red_circle:
   ros2-gbp/google_benchmark_vendor-release#1
- [x] `qt_gui_core` :red_circle: 
   ros2-gbp/qt_gui_core-release#1
- [x] `rmw_connext` :red_circle:
   ros2-gbp/rmw_connext-release#3
   ros2-gbp/rmw_connext-release#4
- [x] `rmw_implementation` :link: :red_circle:
   ~~ros2-gbp/rmw_implementation-release#7~~
   ros2-gbp/rmw_implementation-release#8
   ros2-gbp/rmw_implementation-release#9
- [x] `rosbag2` :red_circle: 
   ros2-gbp/rosbag2-release#6
- [x] `rosidl_typesupport`:link: :red_circle:
   ros2-gbp/rosidl_typesupport-release#6
   ros2-gbp/rosidl_typesupport-release#7
   ros2-gbp/rosidl_typesupport-release#8
- [x] `ros_workspace` :boot: :red_circle:
   ros2-gbp/ros_workspace-release#1
- [x] `rqt_plot` :red_circle:
   ros2-gbp/rqt_plot-release#1
- [x] `rviz` :back:
   ~~ros2-gbp/rviz-release#10~~
   ~~ros2-gbp/rviz-release#11~~

Legend:
- :boot: Boostrap
- :back: Backport
- :red_circle: RedHat-specific workaround (RPM/RHEL/CentOS/Fedora)
- :link: Group resolution
- :question: Other

**Comment by clad26** [comment]
Does this mean we're getting ROS2 on Fedora soon？

**Comment by cottsay** [comment]
> Does this mean we're getting ROS2 on Fedora soon?

We don't *currently* have any plans to release official Fedora packages for ROS 2, but we haven't really discussed it. We're shooting for at least some CentOS packages soon, though, which will give us an idea of what the maintenance burden will be like. Stay tuned.

**Comment by gavanderhoorn** [comment]
You must have internal/private users of all this infrastructure, otherwise you would not be spending all this effort, correct @cottsay?

**Comment by clad26** [comment]
Not being able to use ROS2 or Ignition Software on Fedora (or most linux distros other than Ubuntu) sucks...

**Comment by clad26** [comment]
https://github.com/JuliaPackaging/BinaryBuilder.jl
Might help in building binaries for every Linux distro in general.

**Comment by clalancette** [comment]
> Not being able to use ROS2 or Ignition Software on Fedora (or most linux distros other than Ubuntu) sucks...

For what it is worth, it is possible to use ROS 2 on Fedora if you build from source.

Also, you can do your development inside of containers.  A lot of people (including myself) run whatever they want as the host distribution, but then use LXC or Docker to do their actual ROS development.

> https://binarybuilder.org/
> Might help in building binaries for every Linux distro in general.
> Really easy easy to use too！

Yeah, there are a lot of options out there for building binaries for various Linux distributions.  The problem is that we have a pretty customized build system currently, and switching to anything else would be a very large effort (and possibly be disruptive to the community).

That's not to say it isn't worth investigating, but someone would need to step up and do a lot of research and work to figure out  what it would take to switch.

**Comment by cottsay** [comment]
All of these patches are merged and building successfully on the pre-production farm, so I'm closing this issue.

**Comment by clad26** [comment]
@cottsay 
So... CentOS is kinda dead(ish)
Any update for native Fedora binaries?

**Comment by cottsay** [comment]
> So... CentOS is kinda dead(ish)

The target has always been RHEL and RHEL clones - CentOS is just the specific clone we're using to build the packages (following in EPEL's footsteps). We're also targeting RHEL 7, which is largely unaffected by the recent missteps by the CentOS project.

> Any update for native Fedora binaries?

Nothing has changed. I think we need to see how the RHEL packages go, and gauge how much it costs to maintain an additional RPM distribution in both time and raw compute costs before we could even start that discussion.

If I have anything to share, I'll do it on Discourse.
