### ISSUE TITLE
Type Description Distribution (REP-2011 subset / REP-2016) - formerly "message definitions on-the-wire"

### ISSUE THREAD

**Issue by emersonknapp** [ros2/ros2#1159]
#### Feature description

This feature is a subset of the functionality now described in REP-2011 ros-infrastructure/rep#358

1. Provide an equivalent of the ROS 1 message hashsum to detect message definition mismatches across topics. 
2. Provide a way to discover and communicate the definition of message types from remote topics at runtime.

Use Cases
* Record and store definitions for messages in `rosbag2` for inspection of bags on systems that may not have message definitions installed, or whose local definitions of messages may have evolved since recording
* Inspect messages in off-host visualization tools - such as RViz, Foxglove Studio, and Webviz, for plotting or printing of message contents

#### Implementation considerations

Reference spec in REP-2011 ros-infrastructure/rep#358

### TODO

Based on current state of REP-2011 design and implementation discussion, this list will keep up to date

* [x] Finalize REP-2011 design (for this feature subset)
    * https://github.com/wjwwood/rep/pull/7
    * https://github.com/wjwwood/rep/pull/8
* [x] `TypeDescription` interfaces for representing and communicating type info
    * https://github.com/ros2/rcl_interfaces/pull/146
* [x] Type Hash
    * [x] Hash type description at code generation time
        * https://github.com/ros2/ci/pull/695
        * https://github.com/ros-infrastructure/ros2-cookbooks/pull/52
        * https://github.com/ros2/ros2_documentation/pull/3356
        * https://github.com/ros2/rosidl/pull/722
    * [x] Hash TypeDescriptions at runtime
        * https://github.com/ros2/rcutils/pull/408 
        * https://github.com/ros2/rcl/pull/1027
    * [x] Expose type hashes to typesupport
        * https://github.com/ros2/rosidl_typesupport_fastrtps/pull/95
        * https://github.com/ros2/rosidl/pull/729
        * https://github.com/ros2/rosidl_typesupport/pull/135
        * https://github.com/ros2/rosidl_typesupport_fastrtps/pull/98
    * [x] Distribute type hashes during discovery
        * https://github.com/ros2/rmw/pull/348
        * https://github.com/ros2/rmw_dds_common/pull/70
        * https://github.com/ros2/rmw_fastrtps/pull/671
        * https://github.com/ros2/rmw_cyclonedds/pull/437
        * https://github.com/ros2/rmw_connextdds/pull/104
* [x] Type Description and Raw Sources code generation
    * https://github.com/ros2/rosidl/pull/732
    * https://github.com/ros2/rosidl/pull/727
    * https://github.com/emersonknapp/rosidl/pull/10
    * https://github.com/ros2/rosidl_typesupport/pull/141
    * https://github.com/ros2/rosidl_typesupport_fastrtps/pull/101
    * https://github.com/ros2/rmw_fastrtps/pull/680
    * https://github.com/ros2/rmw_connextdds/pull/113
    * https://github.com/ros2/rmw_cyclonedds/pull/448
    * https://github.com/ros2/rcl/pull/1053
* [x] (For Iron Freeze) Type Description distribution
    * https://github.com/ros2/rcl_interfaces/pull/153
    * https://github.com/ros2/rcl/pull/1060
    * https://github.com/ros2/rclpy/pull/1110
    * https://github.com/ros2/ros2cli/pull/822
    * https://github.com/ros2/rclcpp/pull/2137

Post-Iron Followups (to be backported to Iron)
* [x] Type Hash Distribution (`get_type_description` service)
    * [x] C core
      * https://github.com/ros2/rcl/pull/1052
    * [x] C++ client exposure
      * https://github.com/ros2/rclcpp/pull/2224
      * https://github.com/ros2/system_tests/pull/520
    * [x] Python client exposure
      * https://github.com/ros2/rclpy/pull/1139
      * https://github.com/ros2/ros2cli/pull/838
* [ ] CLI access to type description / hash
    * https://github.com/ros2/ros2cli/pull/817
    * https://github.com/ros2/rclpy/pull/1104
    * https://github.com/ros2/ros2cli/pull/816

#### Related Issues

ros2/rosbag2#782

**Comment by defunctzombie** [comment]
Worth noting that in this functionality exists in ROS1. When a subscriber connects to a publisher, the publisher sends the message definition for the topic.

**Comment by emersonknapp** [comment]
Notes from Middleware WG discussion:

* (Gerardo) DDS supports this via DDS XTypes and the TypeObject
  * DynamicType API lets you introspect types at runtime
  * (Emerson) is this on top of what we’re already using?
    * (Gerardo) Data type is part of the “TypeCode” field in the discovery of DataWriter.
* (Gerardo) When using XTypes if the types are not convertible you will get an error/warning and the type name is basically ignored.
* (Emerson) is there a new API for dynamic data?
  * (Gerardo) not really, it should just be turned on to get some implicit features, but if you want to use the dynamic type introspection then that is a new API.
* (Emerson) is it being used already?
  * (Gerardo/Andrea) it is on by default in rmw_connextdds
  * (Miguel) It is not on by default, but could be turned on.
  * Not sure about cyclonedds
    * (Joe) On going work
* (Gerardo) There is a type hash similar to ROS 1’s md5sum
  * (Andrea) DDS has a limit on typecode sizes, rmw_connextdds sets it to about ~65kb
* (Gerardo) There is a “type service” where you can request a type code with a “type id”
  * Type service is offered by each participant, but could be offered at a network level too (separate centralized type service host)
* (Emerson) can you get the aggregate message or recursively all of the types
  * (Miguel) you can get either the first level or all of the recursive message definitions
* (William) Could pass message hashsum on UserData if we didn’t want to lean on XTypes API for it. 
  * Could offer a ROS 2 Service by default on nodes that provides the .msg definition - xtypes would get us the .IDL definition which isn’t exactly the same.

**Comment by jhurliman** [comment]
From my reading of documentation and testing, it looks like RTPS type introspection is only available with the "RTI Connext DDS Professional" (https://github.com/ros2/rmw_connextdds) and possibly "eProsima Fast RTPS"  (https://github.com/ros2/rmw_fastrtps) ROS2 middlewares. The default Eclipse CycloneDDS rmw does not send a PID_TYPE_OBJECT parameter during discovery, so type checking is done using the datatype string identifier only.

It seems like the two options are to implement TypeObject support in CycloneDDS, or switch the default connector and enable sending TypeObjects by default. Is one of these paths viable for the Humble release?

**Comment by emersonknapp** [comment]
From discussing with Cyclone representative, my understanding is that TypeObject support is on the immediate roadmap for the next CycloneDDS release. https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/ROADMAP.md shows that 0.9 has "XTypes API". 0.8 release has already gone out. I believe the intention is that Humble will be using CycloneDDS >= 0.9

**Comment by clalancette** [comment]
@emersonknapp We've added this to the Humble project board as something that we expect to get into Humble.  Is it OK if I also assign this ticket to you in order to track this and push it across the line?

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-2021-08-19/22008/1

**Comment by emersonknapp** [comment]
I will accept being assigned, but as a fairly core feature I will need collaboration from OpenRobotics team members to make it happen - at least on the design and review levels, but ideally also some help with implementation when we get to that point.

**Comment by sloretz** [comment]
> Could offer a ROS 2 Service by default on nodes that provides the .msg definition - xtypes would get us the .IDL definition which isn’t exactly the same.

The `rosidl` pipeline first converts `.msg/.srv/.action` files to `.idl` files and then generates code based off of the `.idl` files. It's also possible to create a topic/service/action using only an `.idl` file. I think getting the `.idl` definition would be more appropriate than getting the `.msg/.srv/.action` (if one exists) that was used to generate the `.idl`.

A per-node service that returns an `.idl` for a requested type could be implemented at the `rcl` level so that it is also available to non-DDS RMW implementations. It could be implemented by having the typesupport generators in the rosidl pipeline making the idl available as a string that could be fetched with some API.

**Comment by emersonknapp** [comment]
>  think getting the .idl definition would be more appropriate than getting the .msg/.srv/.action (if one exists) that was used to generate the .idl.

I think this makes sense - and it makes me think it makes sense to go down the `UserData` route for DDS-based RMWs. But, that can be an implementation detail, if we craft the RMW API in such a way that it doesn't expose this information.

**Comment by jhurliman** [comment]
> think getting the .idl definition would be more appropriate than getting the .msg/.srv/.action (if one exists) that was used to generate the .idl.

This would create a tight coupling between ROS2 and DDS that currently doesn't exist. Right now, it's possible to implement a compatible ROS2 node using only RTPS by using ROS2 msgdefs to serialize to/from CDR without any intermediate .idl translation. Here's an example ROS2 implementation that does exactly that: <https://github.com/foxglove/ros2>

If the RMW API was extended to now support querying IDLs by datatype (or by publisher/subscriber, however the final API looks) it would leak the DDS implementation detail out, and now any RMW or ROS2 implementation has to become aware of the `.idl` file format and how to do a lossless translation from idl back to msg. I'd like to avoid writing more parsers and increasing the surface area of the ROS2 API if possible.

**Comment by emersonknapp** [comment]
I may be wrong - but I think there might be an overload of the term "IDL". I think that ROS2 considers there to be an "Interface Definition Language" that is specific to ROS2 - and it is not equivalent to the RTPS/DDS formats. This format is used to do code generation for language-specific structs - as per the design diagram at https://docs.ros.org/en/foxy/Concepts/About-Internal-Interfaces.html#type-specific-interfaces . The packages `rosidl_typesupport_${RMW_IMPLEMENTATION}` are the actual DDS-specific interfaces, so this should more precisely be called "RMW Typesupport formats", whereas the "ROS2 IDL" is universal to all possible RMW implementations.

IIUC, the "ROS2 IDL" is used for specific payloads, e.g. `MyServiceRequest` and `MyServiceResponse` - whereas the `.srv` contains definitions for both of these things. On the other hand, a `.msg` would produce only a single "ROS2 IDL" definition.

Somebody pretty please correct me if that's wrong.

**Comment by jhurliman** [comment]
@emersonknapp that doesn't align with my reading of the code. https://github.com/ros2/rosidl/blob/master/rosidl_adapter/rosidl_adapter/msg/__init__.py is converting from `.msg/.srv/.action` files, ROS 2 message definitions as (loosely) defined at <https://docs.ros.org/en/foxy/Concepts/About-ROS-Interfaces.html> to IDL, an OMG specification defined at <https://www.omg.org/spec/IDL/4.2/PDF> that is tightly coupled to DDS.

**Comment by sloretz** [comment]
> I may be wrong - but I think there might be an overload of the term "IDL" causing confusion.

By IDL I mean [OMG IDL 4.2](https://www.omg.org/spec/IDL/4.2/About-IDL/). ROS 2 message generation first converts from `.msg/.srv/.action` to OMG IDL `.idl` files (done by the `rosidl_adapter` package), and then passes the `.idl` files to code generators. https://design.ros2.org/articles/idl_interface_definition.html . Those files  get installed, have a look at `share/builtin_interfaces/msg/Duration.idl` for example.

> This would create a tight coupling between ROS2 and DDS that currently doesn't exist. Right now, it's possible to implement a compatible ROS2 node using only RTPS by using ROS2 msgdefs to serialize to/from CDR without any intermediate .idl translation.

Is this being done outside of the RMW API? There's no requirement for ROS 2 RMW implementations to use RTPS or CDR. I think [rmw_ecal](https://github.com/continental/rmw_ecal) and [rmw_iceoryx](https://github.com/ros2/rmw_iceoryx/) are a couple examples of non DDS and therefore non RTPS/CDR middlewares.

> on reading the linked design doc even more closely - it seems that .idl is specifically referring to OMG IDL format for DDS

I think part of the decision to use OMG IDL is an assumption that OMG IDL is not specifically for DDS, even if it happens to be used by DDS.

**Comment by emersonknapp** [comment]
> I think part of the decision to use OMG IDL is an assumption that OMG IDL is not specifically for DDS, even if it happens to be used by DDS.

OK, this was not immediately obvious but makes sense.
* ROS 2 uses the OMG IDL as its language for defining messages/services/actions
* Some RMW implementations (including the default) are DDS, and that happens to also use the OMG IDL spec
* non-DDS RMW implementations will also receive the ROS 2 OMG IDL files as input for generating their own internal wire formats, because that's what ROS 2 uses to define its interfaces

**Comment by jhurliman** [comment]
> ROS 2 uses the OMG IDL as its language for defining messages/services/actions

It does not. ROS 2 uses the "ROS2 Message description specification", available at <https://docs.ros.org/en/galactic/Concepts/About-ROS-Interfaces.html>. This is a similar definition format to OMG IDL but it is not the same thing. That's why conversion code exists.

> non-DDS RMW implementations will also receive the ROS 2 OMG IDL files as input for generating their own internal wire formats, because that's what ROS 2 uses to define its interfaces

@foxglove/ros2 deals exclusively with .msg/.srv/.action files. If it received a .idl file it would not know what to do with it.

**Comment by emersonknapp** [comment]
> It does not. ROS 2 uses the "ROS2 Message description specification", 

I think the intention is - "ROS 2 uses OMG IDL as the common basis for implementation of the message/service/action descriptions and therefore it is inherently a part of ROS 2's interface description format" ?

**Comment by jhurliman** [comment]
@emersonknapp is that decision documented anywhere? Why have the `.msg` format if OMG IDL is the official interface description format for ROS 2? There's no current need at all for OMG IDL to create a usable ROS 2 client right now which is why this seems like a major change.

**Comment by jhurliman** [comment]
Circling back to the use cases for this feature request, part of runtime support for message definitions in visualization tools is the ability to show the definition to an end user. Users write `.msg` files, they are not familiar with the implementation detail of OMG IDL and would not understand why this alternative syntax is being shown back to them when they wrote a `.msg` file that looks different.

**Comment by emersonknapp** [comment]
I'm just trying to interpret what I can see in the designs and the implementation of clients based on `rcl`. Maybe @sloretz or perhaps @wjwwood or @clalancette can shed more light than I could.

Enumerating the research hole:

Starting at https://design.ros2.org/articles/interface_definition.html 
> With the transition to use IDL for specifying interfaces in ROS 2 Dashing this article has been superseded by the Interface definition using .msg / .srv / .action files article.

Which is https://design.ros2.org/articles/legacy_interface_definition.html, where there is a "Conversion to IDL" section. The way it's worded seems to be saying that "ROS1 format is a legacy format, here's how we use it in ROS2"
> This article specifies the file format coming from ROS 1 describing the data structures exchanged by ROS components to interact with each other.

> Code is generated for defined interfaces to be usable by different client libraries. Interfaces described using the above format are first converted to IDL. Code generation uses the generated file.

Which points to the article https://design.ros2.org/articles/idl_interface_definition.html, which says
> This article identifies a subset of the Interface Definition Language (IDL) that can be used to describe interfaces between components.

Which to me means "ROS 2 interface language is a subset of OMG IDL"

A question I haven't been able to answer is, "is .msg/.srv/.action -> IDL a reversible operation?". I would agree that we should display definitions to users in the way that they define them, though maybe that doesn't mean that's exactly how they have to be represented in code, as long as we have all the necessary information

**Comment by wjwwood** [comment]
I haven't had time to catch up on all of this, but...

> A question I haven't been able to answer is, "is .msg/.srv/.action -> IDL a reversible operation?".

I'd say probably not. There are things that can be done in IDL that cannot be done in msg/srv/action. If the original source was msg/srv/action, then presumably the resulting IDL could be simple enough to do that reverse transition, but I'm not 100% sure.

**Comment by wjwwood** [comment]
My recollection is that we decided to stop extending the "old rosidl" formats (`.msg`/`.srv`/`.action`), but never deprecate them. If there's a feature that requires new IDL logic that we want to expose, e.g. annotating key fields or unions or something like that, then we'd recommend people use `.idl` files directly rather than try to extend the older formats .

The idea being that `.idl`, especially OMG IDL 4.2+, has all the features we'd ever need and we can parse it and use it as input for other code generation tasks, may that be directly generating C++/Python code or generating another intermediate file that is then used by another tool to do code generation, e.g. we could in theory generate protobuf files based on the `.idl` input.

Soooo

> Which to me reads as "ROS 2 interface language is a subset of OMG IDL"

I think this is right. The `rosidl_adapter` package is responsible for converting to the `.idl` format from the older `.msg`/`.srv`/`.action` interfaces, but after that our whole pipeline expects `.idl` and our parser `rosidl_parser` which parses these `.idl` files only supports a subset of the standard.

@sloretz or @clalancette can correct me if I'm wrong...

**Comment by emersonknapp** [comment]
> then we'd recommend people use `.idl` files directly 

I'm not finding a tutorial that does this - but I do see that `rosidl_generate_interfaces` does take `.idl` files directly https://github.com/ros2/rosidl/blob/master/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake#L24 . 

This is a key bit of information that's been missing from this thread - ROS 2 applications may define all their interfaces without ever using a `msg/srv/action` file, which means there would be no "original" in that sense - and these would be perfectly valid ROS 2 applications. Conversely, all `msg/srv/action` files are converted to IDL before being used "as ROS 2"

**Comment by wjwwood** [comment]
We probably don't have tutorials for this. It's not something we necessarily recommend unless you need it just because there's so many messages already in the `.msg` format and because for like ~90% of use cases the `.msg` format is perfectly fine and easier to read.

> This is a key bit of information that's been missing from this thread - ROS 2 applications may define all their interfaces without ever using a msg/srv/action file

Yeah, I'm not sure of even an example of this, but it is possible for sure.

> which means there would be no "original" in that sense - and these would be perfectly valid ROS 2 applications.

There is an original, it's just `.idl` instead of `.msg`...

> Conversely, all msg/srv/action files are converted to IDL before being used "as ROS 2"

Right, but that's kind of an implementation detail. From the user's perspective it's just that `.idl` or `.msg` can be used, it doesn't matter what our pipeline does with it after. For this interface, if I ask a node to give me the definition for example `sensor_msgs/msg/Image`, I want the original format, whether that be `.idl` or `.msg`. Always returning `.idl` might be ok, but isn't preferable to getting the original imo. Ideally you'd get both maybe if `.msg` was used originally.

**Comment by emersonknapp** [comment]
>  I want the original format

This gets us to the crux of the issue. Is there any way for us to tell, at runtime, the exact text of the original file? i mean, maybe it's ok if comments are stripped, but it probably better if it's presented verbatim as originally written.

Not an expert here - but to do this maybe we need something like:
* `rosidl_adapter` includes the original text as metadata in the output `.idl` file
* Typesupport generation includes that information from the `.idl` file in a place where the RMW implementation can get it, perhaps as a static string in generated code. This probably doesn't need to live in the language-specific generators e.g. `rosidl_generator_cpp`/`rosidl_generator_py` - because it only needs to be parsed at the RMW implementation level so it can be passed along whichever mechanism is used to transmit the definitions. Whatever language is used on the receiving end would then get this definition.

**Comment by wjwwood** [comment]
> This gets us to the crux of the issue. Is there any way for us to tell, at runtime, the exact text of the original file?

Sure the original files are installed. So when you're compiling anything that uses the message it could read that file and embed it in the application or it could look it up at runtime.

For example:

```
% ll /opt/ros/rolling/share/sensor_msgs/msg/Image.*
-rw-r--r-- 1 root root 2.0K Aug 11 08:58 /opt/ros/rolling/share/sensor_msgs/msg/Image.idl
-rw-r--r-- 1 root root 1.5K Aug 11 08:06 /opt/ros/rolling/share/sensor_msgs/msg/Image.msg
```

> rosidl_adapter includes the original text as metadata in the output .idl file

I don't think that's necessary, though it might be convenient.

> Does it make sense to pass along a raw string of the input - since this can be passed through rosidl_adapter/rosidl_parser simply enough to produce usable structures on the receiving end?

I think so. The only thing I could imagine is that this could cause the binaries to get pretty big, but that would only be an issue on embedded targets maybe, where library size is actual a concern.

**Comment by amacneil** [comment]
So based on my read of this thread, are the following statements both true?

- ROS 2 supports using _both_ `.msg` or `.idl` (CDR) as the "source of truth" message definition format stored in codebases
- ROS 2 supports pluggable RMWs which may not depend on CDR (e.g. [rmw_ecal](https://github.com/continental/rmw_ecal))

If so, that seems like a bad leaky abstraction. It seems like ROS 2 should either (a) proclaim `.msg` as the source of truth, and allow RMWs to implement translation from `.msg` to their preferred wire format (i.e. CDR for DDS), or (b) proclaim `.idl` as the source of truth, all RMWs are required to support `.idl` only, with `.msg` only exists as a backwards compatibility layer (ideally phased out over time).

It seems strange to me that there is no clear answer on whether `.idl` or `.msg` is the source of truth for serialization at the RMW layer, and statements above claiming either or both.

**Comment by wjwwood** [comment]
Well, OMG IDL does not necessarily == CDR. It's true they are used together but IDL does not assume the serialization format. I know that's confusing because counter examples aren't like this, e.g. protobuf's idl is somewhat tightly coupled to the serialization format. OMG IDL tries to avoid this coupling by having annotations which can contain "extra" info that might be used by serialization engines or even the middleware (like DDS specifics) but isn't required and the core syntax is just interface declaration.

In this case ROS 2 uses IDL to define the interface only. How that translates to serialization if at all is an implementation detail. 

The only leak is if you use annotations in a DDS/RTPS/CDR specific way and in this case tools that don't understand those annotations can mostly ignore them. 

Does that make more sense?

**Comment by amacneil** [comment]
I see, I missed that distinction.

So essentially my proclamation (b) is accurate - ROS 2 architecturally (at least at rmw layer) speaks full IDL, and `.msg` is only a backwards compatible sugar?

If so, has it been considered to remove the additional layer of abstraction by marking `.msg` as a legacy ROS 1 format and move all new code over to `.idl`? It might be a slight learning curve for people migrating to ROS 2, but it would probably save people time in the long run since it is no longer a safe assumption that user space only needs to deal with `.msg` files.

**Comment by wjwwood** [comment]
So I'd reformat your assertions as:

In ROS 2, a message, service, or action may be defined as either a `.idl` file or a `.msg`, `.srv`, or `.action` file, respectively. 

---

We have a python API which may ingest either `.msg` or `.idl` (limiting it to messages for example) and gives you an object that lets you introspect the message definition. 

Now the problem with this is that you probably want to interpret this message definition in C or C++ or TypeScript, etc. 

For this problem, I always imagined that we would store the description in a more commonly parsed format like XML or even a binary format. 

If you look at the XTypes standard that's exactly what they do. They support IDL, XML, XSD, and the binary format they call the TypeObject. 

See section 7.3: https://www.omg.org/spec/DDS-XTypes/1.3/PDF

We could do something similar where we provide either the original text (either msg or idl depending on the original source) or a JSON representation (for example) or XML copying XTypes or a binary representation (I would recommend our own so as not to leak XTypes as a dependency).

**Comment by sloretz** [comment]
> @emersonknapp is that decision documented anywhere? Why have the .msg format if OMG IDL is the official interface description format for ROS 2?

The move to [OMG IDL was part of the Dashing release](https://docs.ros.org/en/crystal/Releases/Release-Dashing-Diademata.html#rosidl). I'm not sure where that decision is documented, but it's probably in one of the links from this ticket: https://github.com/ros2/rosidl/issues/346

> It seems like ROS 2 should either (a) proclaim .msg as the source of truth, and allow RMWs to implement translation from .msg to their preferred wire format (i.e. CDR for DDS), or (b) proclaim .idl as the source of truth, all RMWs are required to support .idl only, with .msg only exists as a backwards compatibility layer (ideally phased out over time).

I think (b) is mostly the case now. The handling of `.msg/.srv/.action` is a layer on top of the whole process, but it will likely never be phased out all the way. RMWs are required to support `.idl` as that's all they are given when asked to generate the code that converts the C/C++/Python/etc ROS 2 message to/from the RMW's wire format. See [rosidl_typesupport_fastrtps as an example](https://github.com/ros2/rosidl_typesupport_fastrtps/blob/152c360d6f241da75d5acb731d738c08bd419631/rosidl_typesupport_fastrtps_c/cmake/rosidl_typesupport_fastrtps_c_generate_interfaces.cmake#L21); it's given only the `.idl` files.

**Comment by emersonknapp** [comment]
Agreeing with @wjwwood  that supporting both is nice. From looking at the idl files - I'd rather not write them by hand if I don't have to - the `msg/srv/action` syntax is certainly a lot more user friendly for humans both for reading and writing. Much bigger learning curve - and since all the functionality exists already I see no reason why it would need to go away.

For tool-builders however it's a different story and it's more complete to speak IDL - to the example of non-DDS impls,  `rmw_ecal` already understands and does conversions from IDL->protobuf, not from msg->protobuf. https://github.com/continental/rosidl_typesupport_protobuf/blob/master/rosidl_adapter_proto/rosidl_adapter_proto/__init__.py - so that provides a pretty good example that we don't need a CDR dependency to use non-DDS RMW

**Comment by wjwwood** [comment]
I don't think we'll remove the support for msg files. Even if that incurs tooling overhead. Simply because it's a simple format that works well for simple things and it's so ingrained. Perhaps in the far future we could remove it, but in some sense the "original" text is only useful for humans. And really we should provide the already parsed description in a neutral format as I described above. That way the tool only has to parse that representation.

**Comment by wjwwood** [comment]
> to the example of non-DDS impls, rmw_ecal already understands and does conversions from IDL->protobuf, not from msg->protobuf. 

Oh that's a good example, I didn't even know about it.

So, not sure how complete that is, but at least in theory it's something that can be done.

---

Also, if you look at Appendix B from the DDS XTypes standard they define the binary object as an IDL file, which is attractive to me at least, supposing that it uses a the same subset of IDL that we do, perhaps we could just use that more or less as-is. It's more that we need but it also is complete in theory and all of our end points can already parse it and receive it over the wire. At the very least it is a good starting point for our own version of this that doesn't leak XTypes directly.

**Comment by amacneil** [comment]
Makes sense, thanks for the extra context. I not at least understand the argument that this new "runtime message definitions" should return IDL.

It's still unclear to me whether it's better for this API to support "always return IDL" or "return IDL or msg depending on what the original source used". For developer tools (like ours), it might be surprising to the user if they authored a msg definition and we showed them IDL. However, if IDL is what RMW is using to communicate then it's probably the most accurate thing for this API to return.

Another option would be if the msg->IDL conversion was made strictly reversible (only for message definitions which started as msg, assuming this information existed in metadata - if the user hand-authored IDL then obviously we would not support creating msg from it).

**Comment by MiguelCompany** [comment]
@amacneil @wjwwood @emersonknapp 

After reading all your conversations about this, I think we could implement the service call with a parameter saying which definition to return. The service will be something like `TypeDefinitions get_type_definition(string topic_name, TypeDefinitionKindMask requested_definitions)` where `TypeDefinitionKindMask` would be a bit composable mask of an enumeration with values `MSG_DEFINITION, IDL_DEFINITION`, and `TypeDefinitions` would be a `sequence<pair<TypeDefinitionKind, string>>`.

The service will only return the requested definitions (if present). This way we could have tools requesting msg only, idl only, or both. Now that I think about it, having a tool that shows the msg format along with the IDL one would help the users in learning about the IDL format.

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/announcing-live-ros-2-connections-in-foxglove-studio/22278/1

**Comment by danthony06** [comment]
Is there any consensus on how to solve this, or a path to getting consensus? This is a pretty important issue for us, so if there's something we can do to move this along, please let us know.

**Comment by emersonknapp** [comment]
Consensus will only be gained via an actual design review, probably with accompanying proof-of-concept prototype. I have currently committed as AWS Robotics to this feature on the Humble Roadmap https://docs.ros.org/en/rolling/Roadmap.html (to deliver Q1 2022). I expect to start work in October. Please reach out if you would like to collaborate.

My current distillation of this conversation is the following requirements:
* Always make IDL definition available
* If IDL was generated from a msg/srv/action, have that original source available as well
* The above should be a new RMW API against specific participants (to get their definition as-they-know-it)
* Ideally provide a hashsum to avoid passing full definition when it's not needed
* We might be able to use DDS XTypes to implement this API for DDS RMWs (maybe also DDS UserData field)
* As a fallback, or alternate implementation that is RMW-independent, this could be implemented via Service calls

**Comment by jhurliman** [comment]
XTypes will not be able to speak msg/srv/action definitions so it may be a false path, but I haven’t looked closely at DDS UserData or how that is transmitted at the RTPS level.

**Comment by clalancette** [comment]
I'd also like to make sure this functionality is RMW-independent.  Adding too many barriers to a non-DDS RMW doesn't seem like a good long-term strategy.

**Comment by jhurliman** [comment]
Since it looks like there wasn't any movement on this in time for Humble, what is the recommended way of retrieving message definitions (the string contents of a msg/srv/action file) from the local filesystem at runtime? Is there an API to do this, or to at least get the filesystem paths given a datatype? Or do I need to write something from scratch that traverses AMENT_PREFIX_PATH looking for rosidl_interfaces index files?

**Comment by Aposhian** [comment]
Why can Foxglove not simply load message definitions from the filesystem like every other ROS2 tool? Why is a new API needed? Yes, having the capability to inspect bags on systems without the messages is kind of interesting, but in my mind, having standard support for ROS2 custom messages (via the filesystem) is better than no support at all (the current situation). For example, Plotjuggler handles ROS2 custom messages just fine.

**Comment by wjwwood** [comment]
I think tools like plotjuggler or rosbag would love to have this feature too, and not have to load things from the filesystem.

It's a common use case (in my experience) to want to install rosbag (or a similar tool) on a machine and record topics coming from a machine on the robot without having to install the packages that provide the messages onto your local machine too. 

This becomes even more important if you want to record messages from a topic that are out of date, i.e. you have the message package on your filesystem but it's a different version than the remote machine is using.

**Comment by amacneil** [comment]
Cross-linking with REP-2011 which will hopefully provide a solution for this:

- https://github.com/ros-infrastructure/rep/pull/358

**Comment by emersonknapp** [comment]
Just a note for anyone following this issue - implementation PRs for type hash generation and distribution are now ready for review. Distribution portion will need some unit/integration testing but they are working end-to-end by manual tests.

**Comment by emersonknapp** [comment]
Doing a full pass for Type Hash Distribution PRs, making sure there's nothing e.g. glaringly wrong on Windows.

This build includes: ros2/rosidl#722, ros2/rmw#348, ros2/rmw_dds_common#70, ros2/rosidl_typesupport_fastrtps#95, ros2/rmw_fastrtps#671, ros2/rmw_cyclonedds#437, ros2/rmw_connextdds#104

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=18211)](http://ci.ros2.org/job/ci_linux/18211/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=12742)](http://ci.ros2.org/job/ci_linux-aarch64/12742/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=18880)](http://ci.ros2.org/job/ci_windows/18880/)

**Comment by Falimonda** [comment]
Do either the `iron` or `rolling` rosbag2_py APIs already support deserialization of messages without the message type's generated modules being installed on the system as is demonstrated in [the sequential reader test file](https://github.com/ros2/rosbag2/blob/iron/rosbag2_py/test/test_sequential_reader.py#L55) now that the encoded_message_definition can be pulled from the bag file using the reader's get_all_message_definitions method?

If not, is there an open issue or other reference to work being done to perform deserialization using just the encoded_message_definition and serialized data? Doing that seems core to addressing related issues such as [rosbag2/issues/782](https://github.com/ros2/rosbag2/issues/782), but that's been closed and I haven't found examples of it being done.

**Comment by emersonknapp** [comment]
No, that is not implemented. It's not covered by this particular issue, which just covers generating and distributing TypeDescriptions. I think https://github.com/ros2/ros2/issues/1374 , and more specifically "Runtime interface reflection" language. @methylDragon would be able to add more insight to exactly what is implemented or not so far - but I believe we do have the capability, given a `TypeDescription`, to use `rcl` APIs to create a deserializer of some type. There would still be a few steps to being able to use the `rosbag2` stored message definitions, which are still original source text rather than extracted `TypeDescription` - but I think most if not all of the core capabilities do exist.

Feel free to make a new feature request issue on https://github.com/ros2/rosbag2, if one does not exist already!

**Comment by Falimonda** [comment]
Thanks for the feedback. I'll take a look at the existing issues to understand where things stand today.

**Comment by emersonknapp** [comment]
I am going to close this issue as successfully completed. There will be improvements, extensions, tooling etc but the core functionality has been implemented, it will be more useful to track ongoing work in targeted issues for those specific improvements.

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros2-inter-distro-communication-issue-eloquent-to-humble-with-fast-dds/33550/3
