### ISSUE TITLE
Configure and Enable the cpplint QA tool

### ISSUE THREAD

**Issue by wjwwood** [ros2/ros2#12]
We have a tools for checking our code with `cpplint` but it is not configured to our liking yet.

Acceptance Criteria:

- [x] Decide on a configuration with the team
- [x] Address code style changes
- [x] Reenable the linter ament/ament_lint#36

**Comment by dirk-thomas** [comment]
Decided on configuration in ament/ament_lint#31

**Comment by dirk-thomas** [comment]
Updated repos:
- [x] ament/ament_index#6
- [x] ros2/rosidl#42
- [x] ros2/rosidl_dds#27

**Comment by jacquelinekay** [comment]
I will take rttest

**Comment by jacquelinekay** [comment]
@wjwwood will take rclcpp (and other rcl libraries?)

**Comment by dirk-thomas** [comment]
Related ticket to either ignore `runtime/int` errors or update the code to comply with `cpplint`: ament/ament_lint#33

**Comment by dirk-thomas** [comment]
The latest job with cpplint enabled: http://ci.ros2.org/job/ros2_batch_ci_linux/547/ I have update the todo list in the first comment to reflect the repos which need fixing.
