### ISSUE TITLE
use FastRTPS

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/ros2#124]
This tickets collects all necessary steps in order to build ROS 2 with FastRTPS:

* [x] add the eProsima repos: https://github.com/ros2/ros2/pull/116

**Linux:**
* [x] build CI job
  * [x] Docker needs to install missing boost dependencies: https://github.com/ros2/ros2/pull/115
* [x] pass all tests
  * http://ci.ros2.org/job/ros2_batch_ci_linux/389/
  * [x] `fastrtps_cmake_module` and `rmw_fastrtps_cpp` use all common linters but have different code style and fails those tests: https://github.com/eProsima/ROS-RMW-Fast-RTPS-cpp/pull/4
  * http://ci.ros2.org/job/ros2_batch_ci_linux/392/
  * [x] the one failing test (http://ci.ros2.org/job/ros2_batch_ci_linux/392/testReport/(root)/test_publisher_subscriber_cpp__dynamicarrayprimitives__rmw_opensplice_cpp__rmw_fastrtps_cpp/test_publisher_subscriber/) is due to the fragmentation and should pass once we increase the default limit in OpenSplice, ros2/rmw_opensplice#85

**OS X:**
* [x] build CI job
  * http://ci.ros2.org/job/ros2_batch_ci_osx/289/
  * [x] fixed handling of unicode characters in `vcstool`
  * http://ci.ros2.org/job/ros2_batch_ci_osx/290/
  * [x] set locale in order for Python not to use `ascii` encoding: https://github.com/ros2/ros2/pull/125
  * http://ci.ros2.org/job/ros2_batch_ci_osx/291/
  * [x] CMake error: https://github.com/eProsima/ROS-RMW-Fast-RTPS-cpp/pull/5
  * http://ci.ros2.org/job/ros2_batch_ci_osx/292/
  * [x] unable to link against `fastrtps` likely because the library location is unknown @richiprosima
  * http://ci.ros2.org/job/ros2_batch_ci_osx/301/
* [x] fix compiler warnings
* [x] pass all tests

**Windows:**
* [x] build CI job
  * http://ci.ros2.org/job/ros2_batch_ci_windows/436/
  * [x] slave needs missing boost dependencies: http://sourceforge.net/projects/boost/, set `BOOST_ROOT` and `BOOST_LIBRARYDIR`, patch CMake find module for Boost to recognize "1.59.0" and "1.59"
  * http://ci.ros2.org/job/ros2_batch_ci_windows/439/
  * [x] install step of `fastrtps` fails @richiprosima
  * http://ci.ros2.org/job/ros2_batch_ci_windows/450/
* [x] fix compiler warnings
* [x] pass all tests

**Know limitations of FreeRTPS:**
* [ ] it does not yet support fragmentation, therefore messages must fit in one UDP datagram (<64k)
  * @richiprosima will work on this feature which will roughly take until the end of 2015 to be implemented

**Comment by dirk-thomas** [comment]
All tests pass on Linux now.

**Comment by dirk-thomas** [comment]
The latest builds passed on all three platforms.

But on OS X and Windows there are some compiler warnings as well as failing tests.

**Comment by dirk-thomas** [comment]
* [x] eProsima/ROS-RMW-Fast-RTPS-cpp#6
* [ ] eProsima/Fast-RTPS#8

**Comment by dirk-thomas** [comment]
Latest set of builds:
* http://ci.ros2.org/job/ros2_batch_ci_linux/578/
* http://ci.ros2.org/job/ros2_batch_ci_osx/462/ (2 times double free warning)
* http://ci.ros2.org/job/ros2_batch_ci_windows/621/ (we can't do cross-vendors tests on Windows anymore, so the tests are only covering rmw_fastrtps_cpp now) I don't know why most executables fail with the rc 3221225781. @richiprosima Any idea?

**Comment by richiprosima** [comment]
Hi Dirk,

I've checked on my Windows. My dll libraries are installed in ${CMAKE_INSTALL_PREFIX}/lib. Although install/local_setup.bat was executed, my libraries weren't found by the system.
I've updated our repositories and now dll libraries are installed in ${CMAKE_INSTALL_PREFIX}/bin.

**Comment by dirk-thomas** [comment]
I triggered another Windows build:
* http://ci.ros2.org/job/ros2_batch_ci_windows/626/

**Comment by richiprosima** [comment]
It keeps on failing in your system.  Can you copy your build options please?

**Comment by dirk-thomas** [comment]
We don't pass any specific options. In this build neither Connext nor OpenSplice is being sourced. It uses the repos defined in https://raw.githubusercontent.com/ros2/ros2/eprosima/ros2.repos. You can see the exact hashed in the console output (after this command `vcs log -l1 "src"`). The build is being started with the following command:

    env.bat "C:\tools\python\python.exe" -u ".\src\ament\ament_tools\scripts\ament.py" build --build-tests --build-space "build" --install-space "install" "src" --isolated

The content of the `env.bat` is shown above the command. It only sets up the Visual Studio environment.

**Comment by richiprosima** [comment]
I use those repos. But I use

 "C:\tools\python\python.exe" -u ".\src\ament\ament_tools\scripts\ament.py" build --build-tests

I will try with yours. 

Thanks

**Comment by dirk-thomas** [comment]
The `--build-space` and `--install-space` arguments are only repeating the default values. The same for the `src` argument. But `--isolated` does make a difference.

**Comment by richiprosima** [comment]
I used `--isolated` and my test results were:

```
88% tests passed, 2 tests failed out of 17

Label Time Summary:
copyright     =   0.64 sec
cppcheck      =   1.06 sec
cpplint       =   1.53 sec
lint_cmake    =   0.64 sec
linter        =   5.09 sec
nose          =  41.28 sec
uncrustify    =   1.22 sec

Total Test time (real) =  50.05 sec

The following tests FAILED:
          1 - test_publisher_subscriber_cpp__rmw_fastrtps_cpp (Not Run)
          2 - test_subscription_valid_data_cpp__rmw_fastrtps_cpp (Not Run)
Errors while running CTest

Stopped after package 'test_communication'

c:\Users\eprosima\ros2>python src\ament\ament_tools\scripts\ament.py test_results
Summary: 43 tests, 0 errors, 0 failures
```
Are boost libraries accessible via PATH environment variable?

**Comment by dirk-thomas** [comment]
Boost was not on the PATH until now. The slave only had the following env variables set:

    BOOST_LIBRARYDIR=C:\local\boost_1_59_0\lib64-msvc-14.0
    BOOST_ROOT=C:\local\boost_1_59_0

I added the lib folder to the PATH and triggered another Windows build: http://ci.ros2.org/job/ros2_batch_ci_windows/641/

**Comment by dirk-thomas** [comment]
Boost was not on the PATH until now. The slave only had the following env variables set:

    BOOST_LIBRARYDIR=C:\local\boost_1_59_0\lib64-msvc-14.0
    BOOST_ROOT=C:\local\boost_1_59_0

I added the lib folder to the PATH and triggered another Windows build: http://ci.ros2.org/job/ros2_batch_ci_windows/646/ (this build does not show compiler warnings since the Jenkins plugin failed to extract them from the FastRTPS build)

**Comment by dirk-thomas** [comment]
@richiprosima The last update has been three weeks ago. The current state is:
* http://ci.ros2.org/job/ci_linux/658/ several tests fail
* http://ci.ros2.org/job/ci_osx/541/ still many compiler warnings and more failing tests then on Linux
* http://ci.ros2.org/job/ci_windows_fastrtps/3/ this job runs without warning parsing since the Jenkins plugin seem to not work well when building FastRTPS, 

What is your ETA to have it build on all platforms without warnings and pass all tests? We would like to announce FastRTPS support in an upcoming alpha release but the date of next one (Alpha 3, Dec 18th.) is approaching fast. several tests fail

Also how is the support for fragmentation coming along? Will it be ready by the end of the month?

**Comment by richiprosima** [comment]
We've updated repository [Fast-RTPS](http://github.com/eProsima/Fast-RTPS) and [ROS-RMW-Fast-RTPS-cpp](eProsima/ROS-RMW-Fast-RTPS-cpp). Also we've created a pull request ros2/system_tests#85.

Now on my linux machine only fails cpplint and uncrustify tests. After running tests ament displays:
```
The following tests FAILED:
     17 - cpplint (Failed)
     19 - uncrustify (Failed)
Errors while running CTest
make: *** [test] Error 8
```
We didn't have time to check it on Windows. We will check next week.

**Comment by dirk-thomas** [comment]
Great, the latest round of jobs (without the PR to system_tests) looks much better:
* http://ci.ros2.org/job/ci_linux/720/ one failing test related to FastRTPS, expected to be fixed with changed sleep times
* http://ci.ros2.org/job/ci_osx/597/ all failing tests are unrelated to FastRTPS
* http://ci.ros2.org/job/ci_windows_fastrtps/4/ multiple failing tests related to FastRTPS, expected to be fixed with changed sleep times

It looks like the listed failed tests on you local machine (`cpplint`, `uncrustify`) are left over result file from earlier runs. I think we removed those linters a while ago: eProsima/ROS-RMW-Fast-RTPS-cpp#4 Have you tried to delete the result file and do those failing tests reappear after running the tests again?

Any updates on fragmentation support?

**Comment by gerkey** [comment]
@wjwwood Please make PR to FastRTPS for upcoming rmw API changes.

**Comment by gerkey** [comment]
@dirk-thomas To add FastRTPS to our CI jobs as a supported rmw implementation.

**Comment by dirk-thomas** [comment]
@richiprosima I have created a pull request to fix the compiler warnings in Fast-CDR: eProsima/Fast-CDR#3

For the remaining warning in Fast-RTPS I am not sure how you want to address them. Many .cpp files define a constant `CLASS_NAME` which isn't used anywhere (e.g. https://github.com/eProsima/Fast-RTPS/blob/master/src/cpp/rtps/builtin/data/ParticipantProxyData.cpp#L39 https://github.com/eProsima/Fast-RTPS/blob/master/src/cpp/rtps/builtin/data/ReaderProxyData.cpp#L24). Can these variables be removed or should the warning be disabled with a scoped pragma?

And one more warning regarding this line: https://github.com/eProsima/Fast-RTPS/blob/eb6ecddf018ddd0552c25a3ed298546e2c4fe92f/src/cpp/rtps/resources/ResourceSendImpl.h#L86 The private variable is set to null in the constructor. Should it be removed or the warning suppressed otherwise?

**Comment by richiprosima** [comment]
@dirk-thomas I have merged eProsima/Fast-CDR#3

Also I have removed warnings you suggested and I have updated the eProsima/Fast-RTPS@c58b2b4 repository.

**Comment by dirk-thomas** [comment]
The newest OS X build looks good - zero warnings: http://ci.ros2.org/job/ci_osx/639/

**Comment by dirk-thomas** [comment]
I have made changes to our CI stuff which allows to cleanly disable any rmw impl.:
* https://github.com/ros2/ros2/pull/171
* https://github.com/ros2/ros2/pull/172
* https://github.com/ros2/ros2/pull/116

**Comment by dirk-thomas** [comment]
@richiprosima Can you please comment on the progress for fragmentation support.

**Comment by dirk-thomas** [comment]
I will close this ticket since we have fully integrated FastRTPS into our CI infrastructure.

Regarding fragmentation support the new ETA from eProsima for the feature is end of May.

**Comment by murikill** [comment]
Hi @dirk-thomas,

may I use ros2-FastRTPS with standalone (non ros2) FastRTPS? Do you have any tips about settings?

Many thanks!

**Comment by dirk-thomas** [comment]
@murikill this is a three year old closed ticket and not the right place to ask random questions. You might want to ask on answers.ros.org (and post a link to your question here for future readers to find it).
