### ISSUE TITLE
ROS 2 Iron Irwini release checklist and development progress

### ISSUE THREAD

**Issue by gbiggs** [ros2/ros2#1298]
For an overview of the development process and an explanation of the major steps, see [this page in the documentation](https://docs.ros.org/en/rolling/Releases/Release-Process.html)

Pre-kickoff (during the last stage of previous release)
---
- [x] Choose a ROS boss: @gbiggs -> @Yadunund 
- [x] Choose a distribution name: [Iron Irwini](https://discourse.ros.org/t/ros-2-i-name-brainstorming/25262)

Development kickoff (approximately June/July)
---
- [x] Create a [page for the release notes](https://docs.ros.org/en/rolling/Releases/Release-Iron-Irwini.html)
- [x] Produce a [release timeline](https://docs.ros.org/en/rolling/Releases/Release-Iron-Irwini.html#release-timeline)
- [x] Create [external release checklist](https://github.com/ros2/ros2/issues/1298)
- [x] [Announce roadmap](https://docs.ros.org/en/rolling/The-ROS2-Project/Roadmap.html#iron-roadmap)

Release kickoff (approximately November-January)
---
- [x] Initial [REP-2000](https://www.ros.org/reps/rep-2000.html) update to set target platforms and dependencies; request feedback from community via Discourse
- [x] Commission distribution artwork
- [x] Commission a `turtlesim` icon
- [x] Create the distribution mailing list

Mid-development cycle
---
- [x] Create the detailed release plan
- [x] Announce upcoming RMW freeze date on Discourse
- [x] Update the Windows packages (bump Python, pinned PIP packages, Visual Studio Code, etc.)
  - [x] Bump [REP-2000](https://www.ros.org/reps/rep-2000.html)
- [x] Upgrade vendored packages to the chosen versions
- [x] Ensure ROS 2 builds on the target platforms and all tests pass
- [x] Freeze the RMW and announce on Discourse

Preparing for release
---
- [x] Announce upcoming branch and overall API-and-feature freeze dates on Discourse
- [x] Announce upcoming beta on Discourse
- [x] Release all packages into Rolling
- [x] Branch from Rolling
  - [x] Add Iron Irwini source branches in each repository
  - [x] Create `ros2.repos` files for Iron Irwini, one for the release and one for development
- [x] Add Iron Irwini to rosdistro
- [x] Add Iron Irwini to [ci.ros2.org](https://ci.ros2.org/)
- [x] Add Iron Irwini to [build.ros2.org](http://build.ros2.org)
  - [x] Enable jobs on [build.ros2.org](http://build.ros2.org/)
- [x] Add Iron Irwini to the documentation as a selectable version
  - [x] Add/update installation pages
- [x] Add Iron Irwini to ROS Index
- [x] Build interim tarballs for testing
- [x] Announce the branch and beta on Discourse
- [x] Create matrix for tracking manual testing

Release week
---
- [x] Announce the artwork on Discourse
- [x] Launch the T-shirt campaign
- [x] Final preparations for the release
  - [x] Get documentation PR ready
  - [x] Get release ros2/ros2 repos file ready
  - [x] Build all packaging jobs
  - [x] Draft PR to update release status on ros/rosdistro
  - [x] Prepare the Discourse post

Release day
---
- [x] Merge PR and make a tag at [ros2/ros2](https://github.com/ros2/ros2)
- [x] Create a release and upload the packaging job artifacts
- [x] Sync the debian packages to main
- [x] Verify that the packages were uploaded to OSU
- [x] Merge rosdistro PR and make a tag
- [x] Update release status on rosdistro
- [x] Announce the release on Discourse
  - [ ] ~~Note that Rolling will soon transition to the next Ubuntu LTS~~
- [x] Create Iron Irwini Docker images
- [x] Close this checklist
- [x] Close the project board

**Comment by Yadunund** [comment]
Iron is released!
