### ISSUE TITLE
Iron Irwini Patch Release 5 Checklist

### ISSUE THREAD

**Issue by Yadunund** [ros2/ros2#1545]
- [x] Bloom binaries for core repos with changes
  - [x] https://github.com/ros/rosdistro/pull/40678
  - [x] https://github.com/ros/rosdistro/pull/40679
  - [x] https://github.com/ros/rosdistro/pull/40680
  - [x] https://github.com/ros/rosdistro/pull/40681
  - [x] https://github.com/ros/rosdistro/pull/40682
  - [x] https://github.com/ros/rosdistro/pull/40683
  - [x] https://github.com/ros/rosdistro/pull/40684
- [x] Fix regressions
  - [x] https://github.com/ros/rosdistro/pull/40721 
  - [x] https://github.com/ros/rosdistro/pull/40726
  - [x] https://github.com/ros/rosdistro/pull/40773
- [x] Update release tags in ros2.repos: https://github.com/ros2/ros2/pull/1546
  - [x] Run CI
  - [x] Run packaging jobs
- [x] Tag rosdistro: https://github.com/ros/rosdistro/blob/iron/2024-04-23/iron/distribution.yaml
- [x] Tag ros2: https://github.com/ros2/ros2/tree/release-iron-20240423
- [x] Run sync job: https://build.ros2.org/job/Irel_sync-packages-to-main/25/
- [x] Create Github release in ros2 with tarballs: https://github.com/ros2/ros2/releases/tag/release-iron-20240423
- [x] Discourse announcement: https://discourse.ros.org/t/patch-release-5-and-new-packages-for-iron-irwini-2024-04-23/
