### ISSUE TITLE
Iron Irwini Patch 6 Checklist

### ISSUE THREAD

**Issue by Yadunund** [ros2/ros2#1582]
- [x] Bloom binaries for core repos with changes
  - [x] https://github.com/ros/rosdistro/pull/42036
  - [x] https://github.com/ros/rosdistro/pull/42037
  - [x] https://github.com/ros/rosdistro/pull/42038
  - [x] https://github.com/ros/rosdistro/pull/42040
  - [x] https://github.com/ros/rosdistro/pull/42041
  - [x] https://github.com/ros/rosdistro/pull/42042
  - [x] https://github.com/ros/rosdistro/pull/42043
  - [x] https://github.com/ros/rosdistro/pull/42044
  - [x] https://github.com/ros/rosdistro/pull/42045
  - [x] https://github.com/ros/rosdistro/pull/42046
  - [x] https://github.com/ros/rosdistro/pull/42047
  - [x] https://github.com/ros/rosdistro/pull/42048
  - [x] https://github.com/ros/rosdistro/pull/42049
  - [x] https://github.com/ros/rosdistro/pull/42050
  - [x] https://github.com/ros/rosdistro/pull/42051
  - [x] https://github.com/ros/rosdistro/pull/42054
  - [x] https://github.com/ros2/rosbag2/pull/1741
- [x] Update release tags in ros2.repos: https://github.com/ros2/ros2/pull/1583
  - [x] Run CI
  - [x] Run packaging jobs
- [x] Tag rosdistro: https://github.com/ros/rosdistro/tree/iron/2024-07-12
- [x] Run sync job: https://build.ros2.org/job/Irel_sync-packages-to-main/31/
- [x] Tag ros2: https://github.com/ros2/ros2/blob/release-iron-20240712/ros2.repos
- [x] Create Github release in ros2 with tarballs: https://github.com/ros2/ros2/releases/tag/release-iron-20240712
- [x] Discourse announcement https://discourse.ros.org/t/patch-release-6-and-new-packages-for-iron-irwini-2024-07-12/38585

**Comment by Yadunund** [comment]
Patch release is out!
