### ISSUE TITLE
Iron Irwini Final Patch and EOL Checklist

### ISSUE THREAD

**Issue by Yadunund** [ros2/ros2#1627]
Checklist to track the progress with releasing the final patch for Iron Irwni before sunsetting the distro.

## Release 
- [x] Bloom binaries for core repos with changes
- [x] Update release tags in ros2.repos
  - [x] Run CI
  - [x] Run packaging jobs
- [x] Tag rosdistro
- [x] Run sync job
- [x] Tag ros2
- [x] Create Github release in ros2 with tarballs: https://github.com/ros2/ros2/releases/tag/release-iron-20241204
- [x] Discourse announcement: https://discourse.ros.org/t/iron-irwini-is-end-of-life/

## EOL
- [x] Mark EOL in ros2_documentation: https://github.com/ros2/ros2_documentation/pull/4894
- [x] Mark EOL in rosdistro: https://github.com/ros/rosdistro/pull/43852
- [x] Mark EOL in rosindex: https://github.com/ros-infrastructure/rosindex/pull/451
- [x] Remove logo from landing page of docs.ros.org
- [x] Wait to check any regressions
- [x] Upload final snapshot
- [x] Disable Iron CI jobs
  - [x] Remove Iron from ros2/ci : https://github.com/ros2/ci/pull/796
- [x] Disable all Iron Buildfarm jobs as per [instructions here](https://github.com/ros-infrastructure/ros_buildfarm/blob/master/doc/ongoing_operations.rst#perform-action-on-a-set-of-jobs)
```
// Disabled by running
import hudson.model.Cause

for (p in Jenkins.instance.allItems) {
  if (
    p.name.startsWith("Isrc_") ||
    p.name.startsWith("Ibin_") ||
    p.name.startsWith("Idev_") ||
    p.name.startsWith("Ibin_") ||
    p.name.startsWith("Idoc_") ||
    p.name.startsWith("Ipr_") ||
    p.name.startsWith("Ici_") ||
    p.name.startsWith("iron_") ||
    p.name.startsWith("Irel_"))
  {
   //  println(p.name)

    p.disable()
  }
}
```
  - [x] Delete Iron jobs from ros2/ros_buildfarm_config: https://github.com/ros2/ros_buildfarm_config/pull/313
  - [x] Delete Iron dashboards: https://github.com/osrf/osr_dashboard/pull/31

**Comment by mjcarroll** [comment]
@Yadunund anything else that needs to happen here?

**Comment by Yadunund** [comment]
We are good to close this 🫡
