### ISSUE TITLE
Create an equivalent to ros::Time

### ISSUE THREAD

**Issue by tfoote** [ros2/ros2#178]
This should provide a standard way to communicate simulated time and present it to the developer through the client libraries in as native a manner as possible.
- [x] create a design document https://github.com/ros2/design/pull/72
- [x] core implementation in rcl https://github.com/ros2/rcl/issues/12
- [x] implement a native cpp interface in rclcpp
  - [x] `rclcpp::Time::now()`: https://github.com/ros2/rclcpp/pull/311
- [x] implement a native c interface in rcl
- [x] implement a native python interface in rclpy https://github.com/ros2/rclpy/issues/186
- [ ] extend use of rclcpp:Time features to existing Rate and Timer https://github.com/ros2/rclcpp/issues/465

**Comment by tfoote** [comment]
Design document: https://github.com/ros2/design/pull/72

**Comment by mikaelarguedas** [comment]
will be picked up in the near future for partial implementation needed for several already in progress tasks (links to be added)

**Comment by tfoote** [comment]
I've ticketed the remaining features in ros2/rclpy#186 and ros2/rclcpp#465 for more specific callouts of what's necessary to close out this meta ticket.

**Comment by sloretz** [comment]
Closing in favor of individual tickets.

It looks like there's only one remaining feature, and it has it's own issue https://github.com/ros2/rclcpp/issues/465 . This meta ticket also overlaps another time meta ticket #530
