### ISSUE TITLE
Alpha 4 release (2016-02-12)

### ISSUE THREAD

**Issue by tfoote** [ros2/ros2#180]
**Alpha 4 feature set**
* [ ] Address Windows test failures
  * [x] build *Release* on Windows fixing Connext tests (also address question of Connext services implementation) (2 weeks) @dirk-thomas ros2/rmw_connext#31
  * [x] allow switching between Debug and Release on Windows @dirk-thomas ament/ament_tools#73
    * [x] add an option to the Jenkins jobs to choose the build type @dirk-thomas ros2/ros2#185
    * [x] export optimized and debug libraries of Connext @dirk-thomas ros2/rmw_connext#123
    * [x] update existing CMake code to pick the matching test executable on Windows @dirk-thomas ament/ament_cmake#55 ament/ament_tools#75 ros2/demos#58 ros2/examples#89 ros2/system_tests#105
* [x] Add support for C data structures in all rmw implementations (1.5 weeks) @wjwwood (~60% done)
  * [x] Write tests that combine the generated code with rcl (0.5 weeks) @wjwwood (~30% done)
* [x] Python client library (just supporting what's in rcl; e.g., not services; start with introspection type support only) (3 weeks) @esteve
  * [x] document C++ and Python type mapping @dirk-thomas ros2/design#76
* [x] Merge https://github.com/ros2/rmw/pull/49 (<1 week)
* [x] Finish real-time requirements document (1 week) @jacquelinekay
* [x] Add some version of ROS time, starting with existing design doc (2 weeks) @tfoote
* [x] Address FastRTPS test failures (1 week)

**Leftover stuff for next time**
* [ ] Fix all test failures
* [ ] Add support for C data structures in Fast and Connext Dynamic rmw implementations @wjwwood 
* [ ] FreeRTPS improvements: RMW support @codebot and @jacquelinekay
  * [x] Autogenerate deserialization (1 weeks)
  * [ ] Tie back into rmw (1 weeks)
  * [ ] Testing/CI for linux case (1 weeks)
    * [x] Add automated tests
    * [ ] Add testing and test reporting to the existing CI job
* [ ] look into cross-talk of libraries (1 week)
* [ ] Support services in C (1.5 weeks) @wjwwood
* [ ] Support parameters in C (2 weeks)
* [ ] Refactor rclcpp to use rcl (2 weeks)
* [ ] Refactor rmw to be more like rcl (3 weeks)
* [ ] Component life-cycle in C++ as defined in the design article (with ROS-agnostic API) (2 weeks)
  * [ ] Introspection and orchestration APIs as ROS topics / services (2 weeks)
    * [ ] Use the orchestration API in launch to make tests deterministic (1 week)
  * [ ] Use C++ program to demonstrate life-cycle and orchestration in a tutorial/demo (1 week)
  * [ ] Use class_loader / pluginlib (1.5 weeks)

**Backlog** *(add tickets from the backlog when being handled)*
* [x] lint design documents @dirk-thomas ros2/design#67 ros2/design#74
* [x] document C++ type mapping @dirk-thomas ros2/design#76

**Comment by tfoote** [comment]
We need to determine how were going to do string encoding. At what level do we provide unicode support for strings? Python it's native C++ it's not...

**Comment by tfoote** [comment]
@dirk-thomas wants to add documentation of message work from last cycle. @jacquelinekay move some freertps stuff into alpha4
