### ISSUE TITLE
Switch to Xenial

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/ros2#217]
This ticket collects everything necessary to switch to Xenial. All branches should be named `xenial` to enable CI testing of all changes together.

For the upcoming Alpha 6 we still aim for Trusty support. So breaking changes shouldn't land before.

* Compile
  * [x] The CI jobs need to be updated to use Xenial instead of Trusty ros2/ros2#216
  * [x] create Debian package of OpenSplice @j-rivero
     * `6.4.0+osrf1-0`[amd64](http://build.osrfoundation.org/view/All/job/opensplice-debbuilder/24/), [i386](http://build.osrfoundation.org/view/All/job/opensplice-debbuilder/25/), [armhf](http://build.osrfoundation.org/view/All/job/opensplice-debbuilder/22/) and [arm64](http://build.osrfoundation.org/view/All/job/opensplice-debbuilder/26/) packages are ready (arm64 still building at this time). Also hosted in [packages.osrfoundation.org](http://packages.osrfoundation.org/gazebo/ubuntu/pool/main/libo/libopensplice64/).
  * [x] fix Python 3.5 issues ros2/rosidl#151
* install new dependencies (`CMake 3.5`) on Windows slaves
  * [x] eatable
  * [x] windshield
* Warnings (run Linux job with branch `xenial` and ci_branch `ci_scripts_xenial`)
  * [x] switch to use upstream `pydocstyle` instead of embedded version and update default warnings ament/ament_lint#49
    * [x] Linux addressed by ros2/ros2#216
    * [x] install pydocstyle on OS X ros2/ros2#221
    * install new dependencies (`pydocstyle`) on Windows slaves
      * [x] eatable
      * [x] windshield
  * [x] allow newer version of `clang-format` if available ament/ament_lint#55
  * [x] operator delete in ros2/examples#107
  * [x] operator delete in ros2/realtime_support#37
  * [x] sign compare in `ament_index_cpp/test/utest.cpp` ament/ament_index#13
  * [x] sign compare in `rcl/test/rcl/test_time.cpp` gtest ros2/rcl#62
  * [x] sign compare in `test_rclcpp/test/test_executor` gtest ros2/system_tests#133

--

* Update wiki pages
  * [x] https://github.com/ros2/ros2/wiki/Linux-Development-Setup/_compare/891a0fb8fa1e181b4734d5a0247703ae67fdae62...33477346803fd6bb921a1df72a4ba3a160ca649b
  * [x] https://github.com/ros2/ros2/wiki/OSX-Development-Setup/_compare/65f5962e18dfff4cce165e0c0c993212928bf264...aa7d88729b27d83d10f3428a0cb132db29fae7ad
  * [x] https://github.com/ros2/ros2/wiki/Windows-Development-Setup/_compare/4e8bc11c720827d54dadc4780dfaefde66d16d39...88cc120e34c22052f0733fa68f369bb0dd613b41
  * [x] install CMake 3.5 https://github.com/ros2/ros2/wiki/Windows-Development-Setup/_compare/f97a2787cd1fdcf6ff8dc066a0e7593813b5f415...cf6a85413fe95530fb0bd40cd4d9439fb9f1f351
  * [x] compiler version https://github.com/ros2/ros2/wiki/Migration-Guide/_compare/4c3a28b83734e96c1ee59c2b07635f1534ff8859...bcd2433ef6846eb12e1983c58544d11ff4b74114
  * [x] mention switch to Xenial https://github.com/ros2/ros2/wiki/Roadmap/_compare/c3c275be4503ab8aff56f055a13b0ce1e10ed969...dd3615b872a5b6b9a4408f43c33c60cdd4c81529

--

* Require Python 3.5, `rclpy` already relies on this new version for the type support extensions
  * [x] https://github.com/ros2/design/pull/91
  * [x] https://github.com/ros2/rclpy/pull/33
  * [x] https://github.com/ros2/rosidl/pull/152

* Require CMake 3.5
  * [x] ament/ament_cmake#72 (and its references)

**Comment by dirk-thomas** [comment]
Using the now available Debian package of OpenSplice the Linux job was able to build with all rmw implementations: http://ci.ros2.org/job/ci_linux/1312/

**Comment by tfoote** [comment]
We need to consider how this will effect our embedded test platforms. @mikaelarguedas and I were talking at the end of last week and realized if we jump forward to Xenial we won't have any ARM test platforms we can test on. 

Almost all of them are on Ubuntu Trusty or Debian Jessie. Xenial support is supposed to come soon, but is not ready yet.

**Comment by tfoote** [comment]
We'll plan to move forward with dropping trusty support in Alpha 7. We expect new base images for the boards in the next 6 months with the newer versions which will allow us to use the newer functionality. We do have the ability to test on arm and arm64 in docker/qemu.

**Comment by dirk-thomas** [comment]
All pull requests are ready to be merged. Waiting for review.

**Comment by dirk-thomas** [comment]
All pull requests are ready to be merged. Waiting for review.

Latest builds show no regressions:
* http://ci.ros2.org/job/ci_linux/1432/
* http://ci.ros2.org/job/ci_osx/1115/
* http://ci.ros2.org/job/ci_windows/1448/

**Comment by dirk-thomas** [comment]
Another set of builds after all PRs have been merged:

* http://ci.ros2.org/job/ci_linux/1450/
* http://ci.ros2.org/job/ci_osx/1132/
* http://ci.ros2.org/job/ci_windows/1465/

**Comment by dirk-thomas** [comment]
@wjwwood Can you please install CMake 3.5 on *dosa*.

**Comment by wjwwood** [comment]
It's done. You know the credentials for dosa are on the internal wiki though...

**Comment by dirk-thomas** [comment]
Sure, but I have no idea how to install a new version of CMake on OS X :wink:

**Comment by dirk-thomas** [comment]
Sure, but I have no idea how to install a new version of CMake on OS X :wink: Thanks

**Comment by jacquelinekay** [comment]
homebrew is still a mystery to me. Might be good to take time to learn about it though. Thanks William :beers:

**Comment by wjwwood** [comment]
https://github.com/Linuxbrew/linuxbrew?

**Comment by wjwwood** [comment]
Ack, that's a stale page: http://linuxbrew.sh/

**Comment by dirk-thomas** [comment]
I have created PRs for all repos regarding CMake 3.5. Since they touch a lot of CMake code I would like to get them merged asap. Please comment on ament/ament_cmake#72 with a plus one after reviewing all the PRs referenced there.

The latest CI builds look good:
* http://ci.ros2.org/job/ci_linux/1466/
* http://ci.ros2.org/job/ci_osx/1141/
* http://ci.ros2.org/job/ci_windows/1476/

**Comment by wjwwood** [comment]
I had a few comments, but I looked over all the pr's and they look good to me.
