### ISSUE TITLE
Alpha 7 on the 8th of July 2016

### ISSUE THREAD

**Issue by tfoote** [ros2/ros2#225]
* [ ] Fix all test failures (or disable flaky tests) (everybody)
  * [x] retry for flaky tests @dirk-thomas #224 #251
  * [x] continue downscoping as needed
* Infrastructure items
  * [x] Update build farm to use newer VS2015 @codebot 
  * [x] migrate to Xenial @dirk-thomas
    * [x] Update to CMake 3.5 @dirk-thomas ament/ament_cmake#72
  * [x] Update to Connext 5.2.3 @dirk-thomas ros2/ros2#232 ros2/ros2#235
  * [x] code coverage for C/C++ using Bullseye or other tools, and Jenkins plugin(s) (like for Gazebo buildfarm)
* [x] Bounded array support for C++ and Python @dirk-thomas ros2/rosidl#158
* [x] FastRTPS  C support  https://github.com/eProsima/ROS-RMW-Fast-RTPS-cpp/pull/27
* [ ] FastRTPS Python support
* [ ] Fix broken cross-vendor system test for FastRTPS and Connext (first cover languages, then cross-languages)
* [ ] Implement wait_for_service @wjwwood https://github.com/ros2/ros2/issues/215
  * [ ] fastrtps
  * [ ] connext_static
  * [x] opensplice
  * [x] apply to rclcpp
* [ ] Support parameters in C ros2/rcl#28 (2 weeks) @jacquelinekay 
  * Various parameter improvements that follow (rclcpp, parameter design, namespace demos, ...)
* [ ] Follower demo / tutorial using TurtleBot 2(.5), focusing on ROS 1 vs. ROS 2 code, structure, and usage, which requires:
  * [ ] ROS 2 wrapper for Kobuki @gerkey including parameterization
  * [ ] ROS 2 wrapper for depth camera (Astra) @tfoote @gerkey
  * [ ] ROS 2 implementation of follower node on x86 @tfoote using depth images into turtlebot2_demo repo
  * [ ] ROS 2 native joystick driver @codebot including parameterization 
  * [ ] Test multi-robot examples, bad wifi, and other ways to demonstrate differences in ROS 2 (kidnapped robot demo)
  * [ ] use launch
  * [ ] command-line dynamic parameter tool (ros2param)

STRETCH GOALS
* [ ] Get first version of rostopic-like functionality, including some graph API, identifying rclpy improvements along the way. @vmayoral https://github.com/ros2/ros2/issues/197
* [ ] ARM SBC-friendly version of follower using depth image, perhaps using OpenCV and/or PCL (probably already done by @tfoote)
* [ ] FreeRTPS improvements: RMW support rename to CMBML migrate to C++999 @codebot (and maybe @jacquelinekay)
  * [ ] Merge history cache and make it work (2 weeks)
  * [ ] Testing/CI for linux case (1 weeks)
    * [ ] Add testing and test reporting to the existing CI job
* [ ] Add doc job at ci.ros2.org (call doxygen, sphinx, whatever)
* [ ] Support Services in Python @wjwwood
* [ ] Refactor type support to have less duplication and easier reuse
* [ ] Refactor rmw to be more like rcl (3 weeks)
* [ ] rosconsole-like replacement for printf (not necessarily wire transport version or other outputs) @dirk-thomas https://docs.google.com/document/d/1ygcs7mPe_O53rXfVHhJC6BKwWOZIwaWIW_8OTmP8LIE
 * [ ] Make arm (32 and 64) CI run nightly without hanging (0.5 week) @gerkey 
* [ ] Improvements for launch (as identified during use).
  * [ ] perhaps including parameters in the YAML/python, other types of static configuration files, etc.

**Comment by kartikmohta** [comment]
Seems like Alpha 7 is already released, are the incomplete items left for next release?

**Comment by Karsten1987** [comment]
can we close this with a remark for alpha-8?

**Comment by mikaelarguedas** [comment]
good point, closing this in favor of #281
