### ISSUE TITLE
Typesupport reloaded

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/ros2#302]
The goal is to avoid the need for separate libraries of `*` (e.g. `rclcpp`, user land code) for each typesupport. Also the obscure method to include the "right" headers using `include_directories` to point to typesupport specific `impl` folders should be removed. This requires the following high level steps:

1. Create "meta" typesupport which knows about all other typesupports, all calls go through this, the requested typesupport is dispatched at runtime (opening the specific typesupport with `dlopen`).
2. The "meta" typesupport can directly refer to a single specific typesupport if only one is supported by all available rmw implementations.
3. Create "meta" rmw in a similar fashion

More detailed list of necessary changes:

  - [x] "meta" typesupport for C++ ros2/rosidl#182
  - [x] "meta" typesupport for C ros2/rosidl_typesupport#6
  - [x] remove dependency of rmw implementations on "meta" typesupport ros2/rmw_fastrtps#85
  - [x] expose symbols for specific typesupports through unified header files ros2/rosidl#196
  - [x] optionally bypass "dispatch" and `dlopen` if only one typesupport is matching the available rmw implementations, the "meta" typesupports need to depend on the rmw implementations for this ros2/rosidl_typesupport#7
    - after this we can try to optionally support linking statically
  - [x] make poco actually optional ros2/rosidl_typesupport#8
  - [x] "meta" rmw implementation ros2/rmw_implementation#17
  - [x] remove rmw specific targets with single targets using `rmw_implementation`, tests need to set the environment variable `RMW_IMPLEMENTATION` to test with non-default implementations ros2/rcl#106
  - cleanup
    - [x] remove `RCLPY_IMPLEMENTATION` logic from `rclpy` ros2/rclpy#66
    - [x] remove obsolete CMake functions from `rcl` / `rclcpp` ros2/rcl#106 ros2/rclcpp#302
    - [x] replace loading mechanism for the rmw implementation in rclpy with something less complex ros2/rosidl#202
    - avoid building rmw specific test targets, some test classes use the rmw name to generate unique test results though
      - https://github.com/ros2/system_tests/blob/5617961025fa9a71fe8c1ec9fdd256801b534107/test_communication/CMakeLists.txt#L301
      - https://github.com/ros2/system_tests/blob/5617961025fa9a71fe8c1ec9fdd256801b534107/test_rclcpp/CMakeLists.txt#L96-L134
  - [x] Update docs / tutorials / wiki
  - [x] Update `rmw_opensplice` to at least build again ros2/rmw_opensplice#161
  - [ ] deduplicate code (e.g. `rosidl_typesupport_c|cpp/type_support_map.h`, CMake)

**Comment by dirk-thomas** [comment]
I have updated the two wiki pages I found with instructions to choose the rmw implementation using the new environment variable:

* https://github.com/ros2/ros2/wiki/Linux-Development-Setup/_compare/f011c1e084fe2faaf4d39b5d89c35722ef2520bd...8ca2ff8b1cd167c131576596fbdadeda2bec3317
* https://github.com/ros2/ros2/wiki/Working-with-multiple-RMW-implementations/_compare/d3d74a1c968753aedd638bba5a3c97aeadef6a63...8ca2ff8b1cd167c131576596fbdadeda2bec3317

I kept the previous information for beta 1 and before as a subsection.

**Comment by dirk-thomas** [comment]
I have addresses almost all the bullets by now.

The two packages `test_communication` and `test_rclcpp` build several tests for each RMW impl. But since the gtests use a define of the rmw impl. name to make the results unique they can't be replaced with a single binary easily.

Regarding the duplicated code in C and C++ typesupport packages (especially the CMake code) I will not try to deduplicate this as part of this endeavor. While it would certainly be nice it has been that way for a long time so I don't want to spend any time on this now.
