### ISSUE TITLE
improvements for topic_names_and_types

### ISSUE THREAD

**Issue by wjwwood** [ros2/ros2#361]
This is an aggregate issue for this task.

Tasks:

- modify data structures to support multiple types per topic
- add get_service_names_and_types (and restrict get_topic_names_and_types to topics only)
- expose option to get topic names without demangling them (removing the ROS conventions using in the middleware)

Todo:

- [x] finish connext static changes (still debugging some strange issues)
- [x] make connext dynamic and opensplice compile again
- [x] update bridge
- [x] add get_sevice_names_and_types to rclcpp
- [x] test get_service_names_and_types in rcl (https://github.com/ros2/rcl/issues/145)
- [x] test no_demangle in rcl (https://github.com/ros2/rcl/issues/146)
- [x] update test for avoid_ros_namespace_conventions to use no_demangle (https://github.com/ros2/system_tests/issues/209)
- [x] use "set" instead of "list" in Python and C++ for types (https://github.com/ros2/rclcpp/pull/339#discussion_r122531256) (https://github.com/ros2/ros2/issues/363)

Pr's for what I have already to come shortly.

**Comment by wjwwood** [comment]
Just running some preliminary CI to catch issues I'm missing locally (no bridge and no connext yet):

- Linux:
  - [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2736)](http://ci.ros2.org/job/ci_linux/2736/)
- Linux-aarch64:
  - [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=273)](http://ci.ros2.org/job/ci_linux-aarch64/273/)
- macOS:
  - [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2202)](http://ci.ros2.org/job/ci_osx/2202/)
- Windows:
  - [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=2867)](http://ci.ros2.org/job/ci_windows/2867/)

**Comment by dirk-thomas** [comment]
I am not sure about the change to allow multiple different types per topic. In DDS it is clearly feasible. In ROS 1 it is not. Several "concepts" are based on this in ROS. E.g. when printing a message using `rostopic echo` you currently only specify the topic name. The same when e.g. visualizing data in `rqt_plot`, you pass `/topic/array_field[2]`. Those kind of interfaces need to change in order to support multiple different types per topic.

We should carefully consider how these are affected and need to be changed and what that means for migration / bridging before changing this.

**Comment by wjwwood** [comment]
Since we don't have a central name service, we don't have an easy way to enforce topics have only one type. Until we come up with a way to do that, I think the information needs to be exposed, because it can (and so probably will) happen. It is useful to see from the tools that there is more than one type on the topic (indicates a problem).

Tools like echo, the bridge, etc. can just assert that only one type is associated with the topic and give up otherwise. In fact @mikaelarguedas and I were talking about that at lunch, and I have a pending change to my ros2cli pr that does that for echo. I'll make one for the bridge too, which just prints a warning if a topic has more than one type on it.

**Comment by wjwwood** [comment]
Ok, I think the rest of these items can and should be ticketed for implementation later. Most are functions that aren't required for the cli or are just improvements to the tests. So I'm putting these all in review.

Here is CI:

- Linux:
  - [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2756)](http://ci.ros2.org/job/ci_linux/2756/)
- Linux-aarch64:
  - [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=290)](http://ci.ros2.org/job/ci_linux-aarch64/290/)
- macOS:
  - [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2228)](http://ci.ros2.org/job/ci_osx/2228/)
- Windows:
  - [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=2884)](http://ci.ros2.org/job/ci_windows/2884/)

**Comment by wjwwood** [comment]
The macOS warnings are related to https://github.com/ros2/rcutils/issues/32.

**Comment by wjwwood** [comment]
@ros2/team bump on reviews for these. I need time to address comments and turn CI around before the cutoff. If you have time, say something here (to prevent multiple people from doing the review).

**Comment by dirk-thomas** [comment]
I went through all the PRs. Due to the amount my "review" was likely more on the shallow side :wink: I made a few minor comments. Overall it looks good to me :+1:

**Comment by wjwwood** [comment]
Thanks @dirk-thomas! I think I've addressed all the comments, here's new CI:

- Linux:
  - [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2759)](http://ci.ros2.org/job/ci_linux/2759/)
- Linux-aarch64:
  - [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=292)](http://ci.ros2.org/job/ci_linux-aarch64/292/)
- macOS:
  - [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2232)](http://ci.ros2.org/job/ci_osx/2232/)
- Windows:
  - [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=2889)](http://ci.ros2.org/job/ci_windows/2889/)

And a Linux packaging job (to test the bridge):

- Linux packaging:
  - [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux&build=17)](http://ci.ros2.org/job/ci_packaging_linux/17/)

**Comment by wjwwood** [comment]
Windows job got disconnected (restarted) and the Linux packaging job has a test failure. I'm looking into that now.

The macOS compiler warnings are expected for now.

**Comment by wjwwood** [comment]
Ok, I fixed the bridge issue, here's one more CI (hopefully last):

- Linux:
  - [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2763)](http://ci.ros2.org/job/ci_linux/2763/)
- Linux-aarch64:
  - [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=295)](http://ci.ros2.org/job/ci_linux-aarch64/295/)
- Linux packaging:
  - [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux&build=18)](http://ci.ros2.org/job/ci_packaging_linux/18/)
- macOS:
  - [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2236)](http://ci.ros2.org/job/ci_osx/2236/)
- Windows:
  - [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=2894)](http://ci.ros2.org/job/ci_windows/2894/)

I will merge if these look good.

**Comment by wjwwood** [comment]
Windows test failure is known flakey.

**Comment by wjwwood** [comment]
I've merged all the pr's and opened issues for all the leftover items I knew about.
