### ISSUE TITLE
Tracking bug to fix memory leaks in test_graph.cpp

### ISSUE THREAD

**Issue by clalancette** [ros2/ros2#387]
I found some memory leaks in ros2/rcl/rcl/test/rcl/test_graph.cpp using valgrind.  The sources of the leaks are spread across a few different repositories, so this is a tracking bug for all of the PRs related to the leaks.  When all PRs are merged, test_graph.cpp has only one small leak from thread creation, which I have not tracked down.  I'll update this bug as the PRs get filed/merged.

- [x] Leaks in rcl (ros2/rcl#158)
- [x] Leaks in rclcpp (ros2/rclcpp#354)
- [x] Leaks in rcutils (ros2/rcutils#48)
- [x] String and signedness fix in rmw (ros2/rmw#118)
- [x] Leaks in rmw_fastrtps_cpp (ros2/rmw_fastrtps#141)

Here's a CI job for the lot of them:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2979)](http://ci.ros2.org/job/ci_linux/2979/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=418)](http://ci.ros2.org/job/ci_linux-aarch64/418/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2408)](http://ci.ros2.org/job/ci_osx/2408/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3088)](http://ci.ros2.org/job/ci_windows/3088/)

**Comment by clalancette** [comment]
I'm actually going to run another CI job, because there have been enough changes (between review and me finding another couple of leaks) that I think it is a good idea:

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2981)](http://ci.ros2.org/job/ci_linux/2981/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=419)](http://ci.ros2.org/job/ci_linux-aarch64/419/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2409)](http://ci.ros2.org/job/ci_osx/2409/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3089)](http://ci.ros2.org/job/ci_windows/3089/)

**Comment by clalancette** [comment]
All of these leaks fixed, closing.

**Comment by dhood** [comment]
I want to comment here with some notes in case it's useful one day looking back. (sometimes I know I've seen an error but can't remember which job it was in and this seems like an appropriate place to comment -- don't mean for this to take away from your work @clalancette!).

On linux, the test used [to fail with](http://ci.ros2.org/view/nightly/job/nightly_linux_repeated/718/testReport/(root)/projectroot/test_graph__rmw_fastrtps_cpp/)
```
*** Error in `/home/rosbuild/ci_scripts/ws/build/rcl/test/test_graph__rmw_fastrtps_cpp': double free or corruption (fasttop): 0x00007fe76c002300 ***
```

But it can still [fail with](http://ci.ros2.org/view/nightly/job/nightly_linux_repeated/751/testReport/junit/(root)/projectroot/test_graph__rmw_fastrtps_cpp/)
```
*** Error in `/home/rosbuild/ci_scripts/ws/build/rcl/test/test_graph__rmw_fastrtps_cpp': free(): invalid pointer: 0x00007f4544002e60 ***
```

or [fail with](http://ci.ros2.org/view/nightly/job/nightly_linux_repeated/752/testReport/junit/(root)/projectroot/test_graph__rmw_fastrtps_cpp/)
```
*** Error in `/home/rosbuild/ci_scripts/ws/build/rcl/test/test_graph__rmw_fastrtps_cpp': munmap_chunk(): invalid pointer: 0x00007fc1200027a0 ***
```

On OSX it [still fails with](http://ci.ros2.org/view/nightly/job/nightly_osx_repeated/793/testReport/junit/(root)/projectroot/test_graph__rmw_fastrtps_cpp/)
```
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
```

**Comment by clalancette** [comment]
@dhood Ug, nasty.  Thanks for the heads up; I thought I had caught all of these, but clearly not!  I'll take another look later this week.  For now I'll leave this bug closed and if I find something new, I'll open a new bug for it.
