### ISSUE TITLE
Tracking bug for runtime package for rosidl

### ISSUE THREAD

**Issue by clalancette** [ros2/ros2#393]
This is a tracking bug to deal with moving runtime dependencies of generated message code in C++ and python into separate packages, so that we don't have the entire `rosidl_generator_*` packages as runtime dependencies.

- [ ] Add the `rosidl_runtime_cpp` package to the https://github.com/ros2/rosidl repository
- [ ] Add the `rosidl_runtime_py` package to the https://github.com/ros2/rosidl repository
- [ ] Change all of the repositories that generate messages to export a dependency on `rosidl_runtime_cpp` (these can be merged in any order):
  - [ ] common_interfaces
  - [ ] demos
  - [ ] example_interfaces
  - [ ] geometry2
  - [ ] rclcpp
  - [ ] rcl_interfaces
  - [ ] system_tests
  - [ ] cartographer_ros

**Comment by mikaelarguedas** [comment]
Can you please propagate the github labels to the new repo as well ? https://github.com/ros2/ros2/issues/389

**Comment by mikaelarguedas** [comment]
I think that you will need to also update the repositories that generate messages in the turtlebot2_demo.repos file

**Comment by clalancette** [comment]
> Can you please propagate the github labels to the new repo as well ? #389

Github labels are now setup properly.

**Comment by clalancette** [comment]
> I think that you will need to also update the repositories that generate messages in the turtlebot2_demo.repos file

I did a quick scan through those repositories.  Of the additional ones in turtlebot2_demo.repos, only ros2/navigation, ros2/ros_astra_camera, and ros2/cartographer_ros have .msg or .srv files.  The navigation .msg files are all in parts of navigation that aren't currently being used in ROS2.  Ditto for ros_astra_camera.  That just leaves ros2/cartographer_ros, which I'll add to the list above.  Thanks!

**Comment by dirk-thomas** [comment]
Beside `rosidl_runtime_cpp` we will also require a `rosidl_runtime_c` (assuming we want to provide the same concept in C). I am just not sure if it makes sense to create new repos for each of these. Why not add them to the existing `rosidl` repo?

**Comment by clalancette** [comment]
Sure, that is fine too.  If you think that is a better way to go, then I'll close out the current one and move it into rosidl.  @mikaelarguedas Sorry for the false start, I'll be opening a new PR very similar to the old one (but in rosidl instead) soon.

**Comment by dirk-thomas** [comment]
Currently some of the generator packages contain header file / Python modules which are needed at runtime from message packages. Those should be moved into the newly create runtime packages.

The goal should be that message packages only build depend on `rosidl_default_generators` and only run depend on `rosidl_default_runtime` (which doesn't need to depend on any generator). They shouldn't depend on any of the language specific generators / runtimes. So when installing Debian packages the user wouldn't need any generator package for just running stuff.

**Comment by dirk-thomas** [comment]
> Currently some of the generator packages contain header file / Python modules which are needed at runtime from message packages. Those should be moved into the newly create runtime packages.

> The goal should be that message packages only build depend on `rosidl_default_generators` and only run depend on `rosidl_default_runtime` (which doesn't need to depend on any generator). They shouldn't depend on any of the language specific generators / runtimes. So when installing Debian packages the user wouldn't need any generator package for just running stuff.

If this is too far reaching for this ticket I would suggest not to create the runtime packages for now and declare the necessary symbols in the generators. That would separate the two orthogonal enhancements without ending up in an in-between state.

**Comment by mikaelarguedas** [comment]
> The goal should be that message packages only build depend on rosidl_default_generators and only run depend on rosidl_default_runtime (which doesn't need to depend on any generator). They shouldn't depend on any of the language specific generators / runtimes. 

:+1: that will also allow to target specific languages / add languages with minimal changes (ala ROS1, i.e. changing only the default rosidl packages and not have to change every existing message package)

**Comment by mikaelarguedas** [comment]
@clalancette What should we do with the [original meta-ticket](https://github.com/ros2/ros2/issues/367) ? Shouldnt they be the same issue? 
Should https://github.com/ros2/example_interfaces/pull/1 be connected to this ticket as well?

**Comment by clalancette** [comment]
> If this is too far reaching for this ticket I would suggest not to create the runtime packages for now and declare the necessary symbols in the generators. That would separate the two orthogonal enhancements without ending up in an in-between state.

Reducing scope here will definitely help me get this in.  I'm fine with not making the new packages for now, as that should be less changes overall.  I'll go ahead with this plan unless someone objects.

**Comment by clalancette** [comment]
> @clalancette What should we do with the original meta-ticket ? Shouldnt they be the same issue?
> Should ros2/example_interfaces#1 be connected to this ticket as well?

@mikaelarguedas Yeah, I'll close out the original meta-ticket, thanks for the hint.  ros2/example_interfaces#1 is already linked to this ticket via "connects to", and via the checklist above.

**Comment by mikaelarguedas** [comment]
> ros2/example_interfaces#1 is already linked to this ticket via "connects to", 

It "connects to" the wrong ticket that's why it doesnt show up connected to anything on waffle

**Comment by clalancette** [comment]
> It "connects to" the wrong ticket that's why it doesnt show up connected to anything on waffle

Ah, sorry about that!  Fixed now.

**Comment by mikaelarguedas** [comment]
should this be put back in backlog ?

**Comment by clalancette** [comment]
Yeah, I'm not going to touch this again until after Beta 3.  I'll move it now.

**Comment by mikaelarguedas** [comment]
> Yeah, I'm not going to touch this again until after Beta 3. I'll move it now.

:+1: 

Can you also delete the branches of all the referenced closed PRs if you dont need them anymore ?

**Comment by clalancette** [comment]
I'm going to close this out since it is old and confusing.  I'll be opening a new bug to track what we really want to do here.
