### ISSUE TITLE
Tracking bug for message initialization in C++

### ISSUE THREAD

**Issue by clalancette** [ros2/ros2#396]
In porting efforts we've run into several bugs where the zero initialized behavior is relied upon, causing bugs. Having a zero initialization method as a way to make porting less fragile would be valuable. And likely can be used in other cases when the optimization of using uninitialized constructors are not as important.

This is a tracking bug to deal with field initialization of generated message code in C++ (originally discussed in ros2/geometry2#25).

- [x] Change the design article about C++ constructors to mention this optional argument: ros2/design#136 (this is actually "done", but I won't merge it until the implementation is ready to go)
- [x] Change the generator in `rosidl/rosidl_generator_cpp` to include the header file from `rosidl_runtime_cpp`, and generate the constructor with the argument on how to initialize (ros2/rosidl#236)
- [x] Write tests for the generated constructors (ros2/rosidl#236)

**Comment by clalancette** [comment]
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3166)](http://ci.ros2.org/job/ci_linux/3166/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=505)](http://ci.ros2.org/job/ci_linux-aarch64/505/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2523)](http://ci.ros2.org/job/ci_osx/2523/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3218)](http://ci.ros2.org/job/ci_windows/3218/)

**Comment by mikaelarguedas** [comment]
I can't find a meta-ticket for all message initialization regardless of the language so I'm posting here. Feel free to move this comment to the relevant ticket that I couldnt find.
We originally said we didnt need to modify the Python message generation because all messages are initialized by default. But now that we offer the ability to initialize messages with only language default or with default values from msg if they exist and language zeros otherwise I think we should provide the same feature in Python

**Comment by clalancette** [comment]
All of the pieces are now in, we can close this out.

**Comment by mikaelarguedas** [comment]
closing this now that the connected tickets have been closed / merged.
@clalancette will open another ticket to track the changes that could/should be reverted in other repos now that message fields are initialized by default
