### ISSUE TITLE
Logging meta-ticket

### ISSUE THREAD

**Issue by dhood** [ros2/ros2#425]
Steps towards the use of logging API and minimal logger severity configuration [limitations in square brackets].

Minimal functionality
- [x] Logger objects in rclpy https://github.com/ros2/rclpy/issues/103
- [ ] rclpy nodes have loggers associated with them [naming conventions hard-coded]
- [ ] C++ macros wrapping rcutils [specifying logger name instead of logger object]
- [ ] Update demos to use logging [callbacks need access to node logger, C++ passing names not logger object]
- [ ] ROS 2 core using debug logging [no subloggers of nodes' loggers]
---
Demo/documentation
- [ ] Demo of service that sets logger level at runtime for logger name
- [ ] Wiki page on logger configuration
---
C++ logger object
- [ ] Node logger name added to nodes in rcl, wrapped in python
- [ ] C++ macros taking logger object, factory functions
- [ ] ROS 2 core using subloggers from node's logger
---
Enhancements
- [ ] Configuration of non-node loggers' context
- [ ] Improve ease-of-use of accessing node logger from callbacks
- [ ] Wrapping of "throttled" filter in C++ macros

**Comment by DLu** [comment]
The migration guide really should be updated to include some basic usage. It still says to use printf, and it took me an hour to sort through this to figure out the new syntax, and that was once I found this wiki page. 

![exhuasted](https://media.giphy.com/media/gVoQge4JXndPq/giphy.gif)

**Comment by wjwwood** [comment]
> The migration guide really should be updated to include some basic usage.

Sorry the migration guide is out-of-date, but the good news is that it's a wiki so you can edit it:

https://github.com/ros2/ros2/wiki/Migration-Guide/_edit

> and it took me an hour to sort through this to figure out the new syntax, and that was once I found this wiki page.

I understand that the migration guide was misleading, but if you just do a search (I did incognito) for "ros2 logging", you get something like this:

<img width="1440" alt="screen shot 2018-06-27 at 2 26 25 pm" src="https://user-images.githubusercontent.com/100427/42000650-3263cb9c-7a16-11e8-987f-41a1b2a41932.png">

The first hit is this wiki page that @dhood made that explains how to configure logging and links to examples in both C++ and Python:

https://github.com/ros2/ros2/wiki/Logging

The second hit is a wiki page describing the logging demo she made:

https://github.com/ros2/ros2/wiki/Logging-and-logger-configuration

**Comment by wjwwood** [comment]
Also, all of our examples and demos use the new logging syntax if you want to look at them for additional examples of using logging, e.g.:

https://github.com/ros2/examples/blob/f6027edfb3a28f012438d1f2d587d0a980e9341c/rclcpp/minimal_subscriber/not_composable.cpp#L27

**Comment by DLu** [comment]
Thanks for those links, sincerely. Unfortunately, they did not show up in my Google searches for `ros2 ros_info` or `ros2 rclcpp_info`. 

`david.google_fu--`

**Comment by wjwwood** [comment]
No worries, but we're busy in the middle of a release, so we would also (sincerely) appreciate help updating any documentation.
