### ISSUE TITLE
Target bionic (meta)

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/ros2#481]
Get regular CI (fastrtps + connext) running:
- [x] bionic on ROS 2 CI
  - [x] Track down dependency changes
    - [x] OpenSSL
      - [x] use RTIs version for connext https://github.com/ros2/system_tests/pull/263
      - [x] fix sros2 to comply with new system OpenSSL with Fast-RTPS https://github.com/ros2/sros2/pull/44
    - [x] Rviz: 
      - [x] needed to install libfreetype6-dev ~~xorg-dev (should be narrowed down as I dont think we need all that)~~ lixrandr-dev is enough
      - [x] ~~libglu1-mesa -> libglu1-mesa-dev~~ not necessary
  - [x] Update Docker CI to use bionic: https://github.com/ros2/ci/pull/148
    ~~- Not install opensplice on ARM for now~~
    ~~- Disable turtlebot jobs for now~~~
- [x] Fix new warnings
  - [x] Fast-RTPS: https://github.com/eProsima/Fast-RTPS/pull/205
  - [x] orocos_kdl: replace deprecated `std::auto_ptr` with smart pointers: https://ci.ros2.org/job/ci_linux/4231/warnings23Result/package.-212634140/
https://github.com/orocos/orocos_kinematics_dynamics/issues/104
- [x] Fix new test failures:
  - [x] Array and parameter segfault https://github.com/ros2/rclcpp/issues/464 https://github.com/ros2/rmw_fastrtps/pull/199
  - [x] Hanging gtest https://github.com/ros2/rclcpp/issues/469 https://github.com/ros2/rclcpp/pull/470

Get all nightlies working:
- [x] Track ROS Melodic release and enable TB2 ci once packages are available
   - 2 options:
     - [X] get kobuki drivers released in melodic: targetting this option for now
     ~~- [ ] get ROS 2 version of ecl + kobuki drivers in ROS 2 and use those debs~~ this is now moved to the optional section below

Get all jobs working:
- [x] Build opensplice debs for bionic
  - [x] amd64
  - [x] arm64

After migration: Cleanup dependencies and hacks:
  - [x] create bionic distro on the ros2 apt repo and stuff it with our arch independent packages
  - [ ] Update osrf source docker images to use bionic as base image: ~~WIP: https://github.com/osrf/docker_images/pull/128~~ https://github.com/osrf/docker_images/pull/160
  - [ ] stop building from source whatever comes with a high enough version
    - [ ] assimp https://github.com/ros2/rviz/issues/248
    - [ ] console_bridge
    - [ ] curl
    - [x] poco rather than requiring both Release and Debug libraries installed
       - we now use the released version of poco in poco_vendor: https://github.com/ros2/poco_vendor/pull/14
    - [ ] tinyxml_vendor
    - ...
  - [x] Check if existing hacks are still necessary: e.g. ~~https://github.com/ros2/ci/commit/d92ec0caffb1e12dd41dbcee82732bd0fcdd7da6~~ hack removed

Optional:

- [x] Install bionic deb for Connext if they get built / released (until then we just use the Xenial one)
- [ ] get ROS 2 version of ecl + kobuki drivers in ROS 2 and use those debs

**Comment by nuclearsandwich** [comment]
Is the plan to drop support for xenial on HEAD the moment that bionic is working or will there be a period of time where we need to support both with the same branch? Of course, ardent will remain a release supported on xenial until bouncy is out. I'm just wondering if we need to test both configurations at once or if we expect all ROS 2 developers to jump to bionic instantly.

**Comment by dirk-thomas** [comment]
`master` is targeting the same platforms as the upcoming Bouncy release. So yes, developers tracking `master` have to move to Bionic.

**Comment by mikaelarguedas** [comment]
First test results with Fast-RTPS only came back:
https://ci.ros2.org/job/ci_linux/4231/testReport/

63 tests failed, all involving rclcpp, seem to fall into 3 categories:
- [ ] SEGFAULT on parameters
- [ ] SEGFAULT on unbounded arrays
- [ ] Change of behavior of Fast-RTPS for secure participants.

I reran the jobs with Fast-RTPS master to be sure this result is not impacted by the fact we changed Fast-RTPS branch earlier today. The results are identical. https://ci.ros2.org/job/ci_linux/4233/testReport/

**Comment by dirk-thomas** [comment]
Just for the record: once this rolled out the following PR can be merged: ament/ament_lint#98.

**Comment by clalancette** [comment]
I spent some time today and tested out the ROS2 Turtlebot2 demo on Bionic.  I'll write a more complete report next week, but the short of it is that I was able to get all of the low-level parts of it working (kobuki node, astra driver, joystick, static_transform_publisher, and depthimage_to_laserscan).  However, cartographer_ros fails to start with:

```
F0525 23:46:33.171504 25516 lua_parameter_dictionary.cc:83] Check failed: status == 0 (2 vs. 0) [string "-- Copyright 2016 The Cartographer Authors..."]:49: attempt to index global 'SPARSE_POSE_GRAPH' (a nil value)
F0525 23:46:33.000000 25516 lua_parameter_dictionary.cc:83] Check failed: status == 0 (2 vs. 0) [string "-- Copyright 2016 The Cartographer Authors..."]:49: attempt to index global 'SPARSE_POSE_GRAPH' (a nil value)
```

It may be a relatively simple fix, but I did not have time to look at it further today.

**Comment by mikaelarguedas** [comment]
The remaining bits for the release are tracked in https://github.com/ros2/ros2/issues/493
The optional task "get ROS 2 version of ecl + kobuki drivers" is out of our control so I'm going to close this
