### ISSUE TITLE
Bouncy Bolson Pre-Release CheckList

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/ros2#493]
Meta ticket tracking things to be done for the Bouncy release

- Kick-off:
  - [x] REP-2000 for bouncy @mikaelarguedas: https://github.com/ros-infrastructure/rep/pull/174

- Infrastructure:
  - [x] upgrade linux buildfarm hosts @nuclearsandwich 
  - [x] configure build.ros2.org smtp @nuclearsandwich
    - [x] contact AWS to get SMTP usage whitelisted
  - [x] create Bouncy distro: @mikaelarguedas
    - [x] ros2/rosdistro: https://github.com/ros2/rosdistro/pull/79
    - [x] ros2/ros_buildfarm_config: https://github.com/ros2/ros_buildfarm_config/pull/5
    - [x] Deploy bouncy management jobs to build.ros2.org
    - [x] update arm node label to pick up bouncy jobs: `buildagent_arm64 || bouncy_binarydeb_ubv8`
  - [x] Release bootstrap packages
    - [x] ament_package https://github.com/ros2/rosdistro/pull/81
    - [x] ament_cmake https://github.com/ros2/rosdistro/pull/84
    - [x] ros_environment https://github.com/ros2/rosdistro/pull/87
    - [x] ros_workspace https://github.com/ros2/rosdistro/pull/86

- [x] Bionic support: details tracked at https://github.com/ros2/ros2/issues/481 @mikaelarguedas

- Packaging:
  - Implement solution for allowing to opt out from multi rmw install
    - [x] with Debian packages: @nuclearsandwich 
      possibilities:
      - put only `build_depend` on the "optional" rmws
      - inject a ~~`Recommends`~~ `Suggests` for the "optional" rmws
    - [x] on macOS from fat archives ros2/ros2#437
  - [x] Extract `catkin_prepare_release` from `catkin` to be used by ROS 2 users @dirk-thomas ros-infrastructure/catkin_pkg#216
    - also not a blocker since the script is available when sourcing ROS 1 as a temporary workaround
  - [x] Audit patches on release repositories
    - [x] NO patch needed: https://github.com/ros2-gbp/ament_package-release/issues/1
    - [x] https://github.com/ros2-gbp/console_bridge-release: We can keep [the existing patch](https://github.com/ros2-gbp/console_bridge-release/blob/2f1918d7c62bb62637076cd66ec4049e192c8ead/xenial/package.xml) as long as we don't create a vendor package for it
    - [x] https://github.com/ros2-gbp/fastcdr-release
      - [x] PR adding package.xml: https://github.com/ros2-gbp/fastcdr-release/pull/1
      While we could have kept the [ardent patch](https://github.com/ros2-gbp/fastcdr-release/blob/bf97d9cb57b071f9879c119341cf6c6fdd4c21fd/xenial/package.xml), the dependency on ament_cmake seemed unnecessary so I removed it and submitted another patch file for bouncy
    - [x] https://github.com/ros2-gbp/fastrtps-release
      - [x] [existing patch](https://github.com/ros2-gbp/fastrtps-release/blob/421ccad3d245e782e569aff3555a6adec9732253/ros2/package.xml) should be kept as is as Fast-RTPS dependencies didn't change
      - [x] Still need to patch `debian/rules.em` to build with `-DSECURITY` after running bloom for the first time
      - [x] Remove examples from installation PR: https://github.com/ros2-gbp/fastrtps-release/pull/4
    - [x] NO patch needed: https://github.com/ros2-gbp/navigation-release/issues/2
    - [x] https://github.com/ros2-gbp/resource_retriever-release PR: https://github.com/ros/resource_retriever/pull/25
    - [x] https://github.com/ros2-gbp/ros1_bridge-release.
      - [x] PR adding dependencies for the packages we want to build the bridge for: https://github.com/ros2-gbp/ros1_bridge-release/pull/1
      - [x] PR adding melodic dependencies and sourcing melodic environment during build https://github.com/ros2-gbp/ros1_bridge-release/pull/2
    - [x] https://github.com/ros2-gbp/poco_vendor-release  PR: https://github.com/ros2/poco_vendor/pull/15
    - [x] https://github.com/ros2-gbp/tinyxml_vendor-release PR: https://github.com/ros2/tinyxml_vendor/pull/10
    - [x] https://github.com/ros2-gbp/rosidl_typesupport-release
      - [x] rosidl_typesupport_c: [add Suggests on vendor typesupport_c packages](https://github.com/ros2-gbp/rosidl_typesupport-release/compare/25c4bea6fdc64e9881f9eef182490acd0716fb08...f8ef61bfb75c5dfc9fbd1844499c4c02fecb024d)
      - [x] rosidl_typesupport_cpp: [add Suggests on vendor typesupport_cpp packages](https://github.com/ros2-gbp/rosidl_typesupport-release/commit/a3b023a082ae54a20a7ca19a87c5a01334e145c2)
    - [x] https://github.com/ros2-gbp/rmw_opensplice-release No patches.
    - [x] https://github.com/ros2-gbp/rmw_implementation-release
      - [x] add runtime depend on any one rmw implementation [commit link](https://github.com/ros2-gbp/rmw_implementation-release/commit/49ae90c91260bd6b4bfb4bf3520fb8991e8ceecc)
    - [x] https://github.com/ros2-gbp/rviz-release patches for vendor shlibdeps
       - [x] rviz2 ([commit](https://github.com/ros2-gbp/rviz-release/commit/3d32bcee9caf1359300523d4823f14025e4ef243))
       - [x] rviz_assimp_vendor ([commit](https://github.com/ros2-gbp/rviz-release/commit/9cd278b577d390477943cfb335544676fd422cb2))
       - [x] rviz_common ([commit](https://github.com/ros2-gbp/rviz-release/commit/157e3879861fcdf1fd6dc951498b3869749b14bd))
       - [x] rviz_default_plugins ([commit](https://github.com/ros2-gbp/rviz-release/commit/1c37322da965bc996f7129cef9935b7d3ecf340d))
       - [x] rviz_ogre_vendor ([commit](https://github.com/ros2-gbp/rviz-release/commit/de19d21d73a0e2ef007d4182d77628e33a5cf45a))
       - [x] rviz_rendering ([commit](https://github.com/ros2-gbp/rviz-release/commit/18399b66687455a0a8148d36f755796527640654))
       - [x] rviz_rendering_tests ([commit](https://github.com/ros2-gbp/rviz-release/commit/fa94565ad13146bebd9220ee6ef6c17cf333d7cc))
       - [x] rviz_visual_testing_framework ([commit](https://github.com/ros2-gbp/rviz-release/commit/eb2af1087d8e3020f60c18afd59e496b30be3151))
       - [x] rviz_yaml_cpp_vendor ([commit](https://github.com/ros2-gbp/rviz-release/commit/fe8cee40211a0f2c2be51c66d69d75bc5ad19621))
    - [x] add links to any other patches applied in the release repo (e.g. suggests)  @nuclearsandwich

  - [x] Propagate ignored files
    - [x] https://github.com/ros2-gbp/urdf-release/pull/1
    - [x] https://github.com/ros2-gbp/rviz-release/pull/2
    - [x] https://github.com/ros2-gbp/orocos_kinematics_dynamics-release/pull/1
    - [x] https://github.com/ros2-gbp/navigation-release/pull/1
    - [x] https://github.com/ros2-gbp/kdl_parser-release/pull/1
    - [x] https://github.com/ros2-gbp/joystick_drivers-release/pull/1
    - [x] https://github.com/ros2-gbp/geometry2-release/pull/1
    - [x] https://github.com/ros2-gbp/cartographer_ros-release/pull/1
    - [x] https://github.com/ros2-gbp/vision_opencv-release (likely not propagate anything and leave it to the Intel team to pick what to ignore or release)

- colcon:
  - [x] release a new version of the colcon packages
  - [x] provide Debian packages
    - [x] import in the ROS apt repos
    - [x] import in the ROS2 apt repos
  - [x] merge design PR ros2/design#168
  - [x] custom logic to avoid leading spaces colcon/colcon-core/issues/36
    only after that has been addressed:
    - [x] update wiki to refer to colcon everywhere #511
    - ~~deprecate `ament_tools` repo~~ post Bouncy release
  - [x] add devel / PR jobs ros2/ros_buildfarm_config#7

- [ ] Dependency management:
  - [x] ASIO: [SRU submitted](https://bugs.launchpad.net/ubuntu/+source/asio/+bug/1771903), keep using system version for now
  - [x] Assimp: waiting on upstream:
    - alternative: keep vendoring it for all platforms
    - workaround to be able to build against upstream: https://github.com/ros2/rviz/pull/288
  - [ ] console_bridge: create a vendor package and use upstream on MacOS and Bionic (optional)
  ~~- [ ] curl: @wjwwood to confirm if vendoring it is still needed~~ the choco package on windows doesn't provide dev libraries
  - [x] poco: use upsream on MacOS: update CI machines 
  - [x] tinyxml2: choco: Update custom choco package to 6.0.0
  - [x] eigen: choco: use 3.3.4 (stable) to avoid https://discourse.ros.org/t/ros-answers-kinetic-uses-unstable-eigen3-on-ubuntu-16-04/4425
  - [x] asio: choco: use 1.12.1 

- [x] Documentation
  - [x] Update tutorials
  - [x] update installation instructions
  - [x] remove mentions to beta1 or earlier from the wiki

- [x] T-shirt campaign
- [x] C-Turtle Name

**Comment by nuclearsandwich** [comment]
> configure build.ros2.org smtp @nuclearsandwich

There's some outstanding DKIM and SPF setup to do for email and I'm still waiting to hear back from AWS about de-throttling smtp

**Comment by dirk-thomas** [comment]
For the bullets under "Audit patches on release repositories" it would be great to have a list of what actual patches are being applied for each of these packages. That would ease reviewing them a lot.

**Comment by mikaelarguedas** [comment]
> For the bullets under "Audit patches on release repositories" it would be great to have a list of what actual patches are being applied for each of these packages. That would ease reviewing them a lot.

For the ones that I audited I put link of the PRs that move the patch to the source repo making the patch in the release repo obsolete.
For the ones that dont have the box checked, that means I didnt evaluate how the patches should be modified for bouncy yet and so there is no description of the patches being applied yet.
The unticked ones fall into 3 categories:
- packages that don't have a package.xml upstream and the patch consists in adding a package.xml
- packages that have different dependencies in the debian case and that we should evaluate (typesupport, rmws etc)
- packages that need extra dependencies only in the debian case: ros1_bridge

**Comment by mikaelarguedas** [comment]
Remaining work vendoring console bridge ticketed at https://github.com/ros2/ros2/issues/521

Closing this
