### ISSUE TITLE
Bouncy Release Checklist

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/ros2#510]
Follow-up of #493 

### Documentation pre-testing

- update documentation outside of the wiki to use colcon instead of ament_tools
  - [x] ros2/ros1_bridge#122
- [x] update tutorials
- [x] update installation instructions
  - [x] update archives supporting connext: [windows](https://github.com/ros2/ros2/wiki/Windows-Install-Binary/_compare/1e3612a9be3d42852bb4854fd6c2610709906182...37d7bcef38bcd8c2a08d17e076735491cadb3da6), [osx](https://github.com/ros2/ros2/wiki/OSX-Install-Binary/_compare/4188057d1a263c4a36f9878b5f9acf3647e17006...11696bbbb2286502bb8bda1e75ed2f46ec1d76a1), [linux](https://github.com/ros2/ros2/wiki/Linux-Install-Binary/_compare/c41d7600dfa3c1d6ac34b831ff1ad85c0d788b9d...ac24e18507445d93be5d6d541d7f3108a3bf9d21)

### Documentation post-testing:

- [x] remove mentions from beta1 and earlier from the wiki

### Testing

- [x] update testing spreadsheet with all new executables and tutorials to test
- [x] perform testing on last packaging artifacts (or from master if building from source) 

### Release packages

- [x] bump version in setup.py if necessary
- [x] level package.xml version and tag the release (`catkin_prepare_release --bump minor`)
- [x] release using bloom:
  * Set the ROS 2 rosdistro index
    ```
    export ROSDISTRO_INDEX_URL='https://raw.githubusercontent.com/ros2/rosdistro/ros2/index.yaml'
    ```
  * `bloom-release <REPO_NAME> -r bouncy -t bouncy -n`
  - [x] repositories to release (github handle next to it comes from the extracted maintainer tags in package.xml) [list of blocked repos](http://repo.ros2.org/status_page/blocked_releases_bouncy.html):
    - [x] ament_cmake	  @dirk-thomas
    - [x] ament_cmake_ros	  @dirk-thomas
    - [x] ament_index	  @dirk-thomas
    - [x] ament_lint	  @dirk-thomas
    - [x] ament_package	  @dirk-thomas
    - [x] ament_tools	  @dirk-thomas
    - [x] angles	  @tfoote
    - [x] cartographer	  @mikaelarguedas
    - [x] cartographer_ros	  @clalancette
    - [x] class_loader	  @mikaelarguedas
    - [x] common_interfaces	  @wjwwood
    - [x] demos	  @dirk-thomas
    - [x] depthimage_to_laserscan	  @clalancette
    - [x] example_interfaces	  @dirk-thomas
    - [x] examples	  @mikaelarguedas
    - [x] geometry2	  @tfoote
    - [x] googletest	  @dirk-thomas
    - [x] joystick_drivers	  @mikaelarguedas
    - [x] kdl_parser	  @clalancette
    - [x] laser_geometry	  @wjwwood
    - [x] launch	  @wjwwood (https://github.com/ros2/rosdistro/pull/107)
    - [x] libyaml_vendor	  @mikaelarguedas
    - [x] navigation	    @dhood
    - [x] navigation_msgs	 @wjwwood
    - [x] orocos_kinematics_dynamics	  <maintainer email="ruben@intermodalics.eu">Ruben Smits</maintainer>
    - [x] osrf_pycommon	  @wjwwood (https://github.com/ros2/rosdistro/pull/106)
    - [x] osrf_testing_tools_cpp	 @wjwwood
    - [x] pcl_conversions	  @clalancette
    - [x] pluginlib	  @mikaelarguedas
    - [x] poco_vendor	  @nuclearsandwich
    - [x] rcl	  @wjwwood
    - [x] rcl_interfaces	  @tfoote
    - [x] rclcpp	  @dirk-thomas
    - [x] rclpy	  <maintainer email="esteve@osrfoundation.org">Esteve Fernandez</maintainer>
    - [x] rcutils	  @Karsten1987
    - [x] realtime_support	  @clalancette 
    - [x] resource_retriever	  @clalancette
    - [x] rmw	  @dirk-thomas
    - [x] rmw_connext	  @dirk-thomas
    - [x] rmw_fastrtps	  @nuclearsandwich
    - [x] rmw_implementation	  @dirk-thomas
    - [x] rmw_opensplice	  @dirk-thomas
    - [x] robot_state_publisher	  @Karsten1987
    - [x] ros_astra_camera	  @clalancette
    - [x] ros_environment	  @dirk-thomas
    - [x] ros1_bridge	  @dirk-thomas
    - [x] ros2cli	  @dirk-thomas
    - [x] rosidl	  @dirk-thomas
    - [x] rosidl_defaults @dirk-thomas 
    - [x] rosidl_dds	  @dirk-thomas 
    - [x] rosidl_python	  @dirk-thomas
    - [x] rosidl_typesupport	  @dirk-thomas
    - [x] rosidl_typesupport_connext	  @dirk-thomas
    - [x] rosidl_typesupport_opensplice	  @dirk-thomas
    - [x] rviz	  @wjwwood
    - [x] sros2	  @mikaelarguedas
    - [x] teleop_twist_joy	  @clalancette
    - [x] teleop_twist_keyboard	  @clalancette
    - [x] tinyxml_vendor	 @nuclearsandwich
    - [x] tinyxml2_vendor	  @wjwwood
    - [x] tlsf	  <maintainer email="jackie@osrfoundation.org">Jackie Kay</maintainer>
    - [x] turtlebot2_demo	  @mikaelarguedas
    - [x] uncrustify	  @dirk-thomas
    - [x] urdf	  @clalancette
    - [x] urdfdom	  <maintainer email="hsu@osrfoundation.org">John Hsu</maintainer>
  - [ ] ensure all jobs including devel jobs are passing and have reasonable results

- [x] check that all released repos have been released with latest commit
- [x] multi rmw implementation debs investigation
- [x] release updated docs
- [x] upload python packages the changed to main

**Comment by nuclearsandwich** [comment]
For packages that need manual dependency work after bloom generates the templates I would like to be the one to run bloom this first time. I'll also be submitting PRs to add package.xml comments which explain what changes are being applied to debian control files before releases are ready.

Packages in the following repositories will need special treatment during bloom

> * rmw @dirk-thomas
> * rmw_connext @dirk-thomas
> * rmw_fastrtps Ricardo González
> * rmw_implementation @dirk-thomas
> * rmw_opensplice @dirk-thomas
> * rosidl @dirk-thomas
> * rosidl_dds @dirk-thomas
> * rosidl_typesupport @dirk-thomas

**Comment by mikaelarguedas** [comment]
Bouncy is now released. @mikaelarguedas to follow up on the unstable dev jobs and auditing the list of remaining patches in the release repos
