### ISSUE TITLE
Functionality around time

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/ros2#530]
- [ ] `clock.sleep_for()` and `clock.sleep_until()` in `rclcpp` and `rclpy` (discussion on where sleep functions should live in ros2/rclcpp#1248, Added issue ros2/rclpy#617)
- [ ] Decide if there should be a way to to enable simtime "globally" (e.g. env. var., global param server, more convenient way to pass parameter to each node)
- [x] `rclpy` `TimeSource` activate rostime when `use_sim_time` parameter is set (issue ros2/rclpy#240)
- [x] Logging macros respecting ROS time ros2/rclcpp#969 ros2/rclcpp#970
- [x] `rclpy` Rate class ros2/rclpy#443
- [x] API on nodes in `rclcpp` and `rclpy` for creating timers with various types [rclpy node.create_timer()](https://github.com/ros2/rclpy/blob/a37c01511324c1e3e57bc47a7e1286bf79514c60/rclpy/rclpy/node.py#L1322-L1328), free function [rclcpp::create_timer()](https://github.com/ros2/rclcpp/blob/01d6f52e3281f6df2c191690527f9208006a5c50/rclcpp/include/rclcpp/create_timer.hpp#L55-L71)
- [x] rclpy timer constructor needs to accept a clock argument [This TODO](https://github.com/ros2/rclpy/blob/514f76b100c789ddc505585310bfb85c1d3381ce/rclpy/rclpy/timer.py#L24-L25) [Done](https://github.com/ros2/rclpy/blob/a37c01511324c1e3e57bc47a7e1286bf79514c60/rclpy/rclpy/node.py#L1327) ros2/rclpy#419

Completed

* Fixed drift in calculation of next timer time (ros2/rcl#291)
* `tf2_ros` uses ROS clock (ros2/geometry2#67)
* rclpy has a Time, Duration, and Clock implementation (ros2/rclpy#209)
* rclpy has a time source abstraction (ros2/rclpy#210)
* rclpy supports clock jump callbacks (ros2/rclpy#222)
* rcl timers initialized with clock (ros2/rcl#272)
* rclcpp timers initialized with clock (ros2/rclcpp#523)
* rclpy timers internally initialized with clock (ros2/rclpy#211)
* rcl clock may have multiple time jump callbacks (ros2/rcl#284)
* Timers in rcl trigger using ROS time (ros2/rcl#286)
* rclcpp `time::max()` and `duration::max()` (ros2/rclcpp#538)
* rclcpp `time::seconds()` (ros2/rclcpp#526)
* rclcpp `duration::seconds()` (ros2/rclcpp#536)
* Don't activate rostime just because clock is being published in rclcpp (ros2/rclcpp#559)

**Comment by dirk-thomas** [comment]
Relevant discusssion: #350.

**Comment by dhood** [comment]
@matt-attack has referenced some work towards timers using simtime in https://github.com/ros2/rclcpp/issues/440 (FYI @dirk-thomas )

**Comment by sloretz** [comment]
Another time ticket ros2/rclcpp#465

**Comment by dirk-thomas** [comment]
I added the following two sub-bullets to the first comment:
* ros2/rclcpp#523 adds the API for timers (except WallTimer) to get initialized with a clock
* next: create API in the Node class to create timers of various types, the node will need to manage one clock instance for each type as long as there are any timers using that clock type

**Comment by sloretz** [comment]
Updated ticket to contain the current state of the time work

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/security-ramifications-of-global-parameter-events/15924/6

**Comment by clalancette** [comment]
@sloretz To go through this one and split out individual tickets for the remaining work, then close.

**Comment by sloretz** [comment]
I've added references to tickets that were complete, and opened a ticket for an issue that wasn't. The only issue without a ticket is

> Decide if there should be a way to to enable simtime "globally" (e.g. env. var., global param server, more convenient way to pass parameter to each node)

I don't know what to do with this one. It appears to be a question about whether there should be a feature rather than a proposal for one. I wasn't able to find an existing ticket - open or closed - about adding a global way to enable sim time.

I'll close this rather than trying to answer that question. If someone thinks there should be a more convenient way to enable sim time globally then I'm assuming they'll open a ticket for it.
