### ISSUE TITLE
Bouncy Patch release 1

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/ros2#537]
Ticket to aggregate the list of tickets that should be fixed and / or backported for the Bouncy first patch release:

## Tickets to address:
- [x] Release Python 3.7 based archives: https://github.com/ros2/ros2/issues/526
- [x] Memory leaks in Python generated code: https://github.com/ros2/rosidl_python/issues/5
- [x] ros2/ros2#544

## PRs to backport
- [x] ros2/rosidl_python#7 (BP PR https://github.com/ros2/rosidl_python/pull/8)
- [x] ros2/rcl#263 (BP PR https://github.com/ros2/rcl/pull/271)
- [x] ros2/rclpy#203 (BP PR https://github.com/ros2/rclpy/pull/208)
- [x] ros2/launch#96 + ros2/launch#99 (BP PR https://github.com/ros2/launch/pull/118)
- [x] ros2/ros2cli#121 (https://github.com/ros2/ros2cli/pull/124)
- [x] ament/ament_cmake#146 (BP PR: https://github.com/ament/ament_cmake/pull/147)
- [x] ros2/rmw_implementation#44 (BP PR: https://github.com/ros2/rmw_implementation/pull/45)
- [x] ros2/turtlebot2_demo#88 (https://github.com/ros2/turtlebot2_demo/pull/89)
- [x] https://github.com/ros/pluginlib/pull/121
- [x] ament/ament_package#80 (https://github.com/ament/ament_package/pull/81)
## Repositories to version bump and release
- `ament_cmake`: https://github.com/ros2/rosdistro/pull/248
- `Fast-RTPS`: https://github.com/ros2/rosdistro/pull/234
- `launch` https://github.com/ros2/rosdistro/pull/236
- `rosidl_python` https://github.com/ros2/rosdistro/pull/244
- `rcl` https://github.com/ros2/rosdistro/pull/245
- `rclpy` https://github.com/ros2/rosdistro/pull/247
- `rmw_implementation` https://github.com/ros2/rosdistro/pull/249
- `ros2cli` https://github.com/ros2/rosdistro/pull/246
- `turtlebot2_demo` https://github.com/ros2/rosdistro/pull/250
- `variants` https://github.com/ros2/rosdistro/pull/243
- `pluginlib` https://github.com/ros2/rosdistro/pull/251
- `ament_package` https://github.com/ros2/rosdistro/pull/253

## Rerun bloom
- `urdfdom_headers` https://github.com/ros2/rosdistro/pull/242

**Comment by mikaelarguedas** [comment]
Out of the 63 PRs merged since bouncy:
## Considered for backport:
https://github.com/ros2/rosidl_python/pull/7 (listed above)
https://github.com/ros2/rclpy/pull/203 (listed above)
https://github.com/ros2/launch/pull/96 (listed above)
https://github.com/ros2/launch/pull/99
https://github.com/ros2/ros2cli/pull/121

## Maybe?
https://github.com/ros2/launch/pull/82 @wjwwood PR description says "doesnt need to be in for bouncy" does that mean no backport?

**Comment by mikaelarguedas** [comment]
> I was hoping to fix the ctrl-c issues with launch and then take all the changes merged so far in launch. Given that it is new and for the most part a leaf packages right now.

That sounds good to me

**Comment by wjwwood** [comment]
After talking with @mikaelarguedas I think we'll just wait and not block this patch release on the launch issue because I don't know how long it will take to fix it.

As for the other patches in `launch` since the release, I think we should just take them all in a `0.5.2` patch release, as they are all small bug fixes in my opinion: https://github.com/ros2/launch/compare/0.5.1...master

**Comment by dirk-thomas** [comment]
Maybe colcon/colcon-core#85 should be implemented, merged, and released before building the fat archives of the patch release?

**Comment by dirk-thomas** [comment]
Maybe colcon/colcon-ros#26 should be reviewed, merged, and released before announcing the patch release.

**Comment by mikaelarguedas** [comment]
Packaging jobs for bouncy patch 1:
 * Ubuntu bionic: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux&build=129)](http://ci.ros2.org/job/ci_packaging_linux/129/)
 * Ubuntu xenial: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux&build=130)](http://ci.ros2.org/job/ci_packaging_linux/130/)
 * Ubuntu aarch64 bionic: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux-aarch64&build=26)](http://ci.ros2.org/job/ci_packaging_linux-aarch64/26/)
 * Ubuntu aarch64 xenial: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux-aarch64&build=27)](http://ci.ros2.org/job/ci_packaging_linux-aarch64/27/)
 * MacOS: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_osx&build=43)](http://ci.ros2.org/job/ci_packaging_osx/43/)
 * Windows: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_windows&build=65)](http://ci.ros2.org/job/ci_packaging_windows/65/)
 * Windows Debug: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_windows&build=66)](http://ci.ros2.org/job/ci_packaging_windows/66/)

**Comment by mikaelarguedas** [comment]
Repos files update:
ros2.repos: https://github.com/ros2/ros2/pull/548
turtlebot2_demo.repos: https://github.com/ros2/turtlebot2_demo/pull/90

**Comment by mikaelarguedas** [comment]
New round with ament_package 0.5.2

 * Ubuntu bionic: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux&build=136)](http://ci.ros2.org/job/ci_packaging_linux/136/)
 * Ubuntu xenial: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux&build=137)](http://ci.ros2.org/job/ci_packaging_linux/137/)
 * Ubuntu aarch64 bionic: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux-aarch64&build=30)](http://ci.ros2.org/job/ci_packaging_linux-aarch64/30/)
 * Ubuntu aarch64 xenial: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux-aarch64&build=31)](http://ci.ros2.org/job/ci_packaging_linux-aarch64/31/)
 * MacOS: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_osx&build=49)](http://ci.ros2.org/job/ci_packaging_osx/49/)
 * Windows: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_windows&build=69)](http://ci.ros2.org/job/ci_packaging_windows/69/)
 * Windows Debug: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_windows&build=70)](http://ci.ros2.org/job/ci_packaging_windows/70/)

**Comment by sloretz** [comment]
There are a couple issues with the xenial archive https://ci.ros2.org/job/ci_packaging_linux/137/
* Python publisher slowly leaks memory
* Could not `ctrl` + `c` `ros2 launch`

If the publisher leak is smaller and `ctrl` + `c` behavior is identical to the current bouncy release then I would say the patch looks ok. I'll check that next.

# Test Results

<details><summary>Python publisher slowly leaks, python subscriber does not leak.</summary>

In one terminal

```python
from time import sleep

import rclpy

from geometry_msgs.msg import Twist


def main(args=None):
    rclpy.init(args=args)

    node = rclpy.create_node('leak_test_publisher')

    publisher = node.create_publisher(Twist, 'topic')

    msg = Twist()

    while rclpy.ok():
        msg.linear.x = 3.14
        msg.angular.z = 2.718
        publisher.publish(msg)

    node.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()
```

In another terminal ran:

```
ros2 topic echo /topic > /dev/null
```

In a third terminal

```
top -o RES
```

The listener's memory usage stayed constant at 48040 Kib. The publisher's memory usage slowly increased from 36904 KiB to 42976 KiB.

</details>


<details><summary>Building rosidl_generator_py has a lot of cmake warnings, but passes</summary>

Roughly ran

```
mkdir -p ros2-xenial/src
cd ros2-xenial/src
git clone https://github.com/ros2/rosidl_python.git
cd ..
colcon build
```

Got stderr output

```
CMake Warning at /home/developer/workspaces/ros2-linux/share/rmw_connext_shared_cpp/cmake/ament_cmake_export_include_directories-extras.cmake:11 (message):
  Package 'rmw_connext_shared_cpp' exports the include directory
  '/opt/rti.com/rti_connext_dds-5.3.1/include' which doesn't exist
Call Stack (most recent call first):
  /home/developer/workspaces/ros2-linux/share/rmw_connext_shared_cpp/cmake/rmw_connext_shared_cppConfig.cmake:38 (include)
  /home/developer/workspaces/ros2-linux/share/rmw_connext_cpp/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /home/developer/workspaces/ros2-linux/share/rmw_connext_cpp/cmake/rmw_connext_cppConfig.cmake:38 (include)
  /home/developer/workspaces/ros2-linux/share/rmw_implementation_cmake/cmake/call_for_each_rmw_implementation.cmake:61 (find_package)
  cmake/rosidl_generator_py_get_typesupports.cmake:26 (call_for_each_rmw_implementation)
  CMakeLists.txt:61 (rosidl_generator_py_get_typesupports)


CMake Warning at /home/developer/workspaces/ros2-linux/share/rmw_connext_shared_cpp/cmake/ament_cmake_export_include_directories-extras.cmake:11 (message):
  Package 'rmw_connext_shared_cpp' exports the include directory
  '/opt/rti.com/rti_connext_dds-5.3.1/include/ndds' which doesn't exist
Call Stack (most recent call first):
  /home/developer/workspaces/ros2-linux/share/rmw_connext_shared_cpp/cmake/rmw_connext_shared_cppConfig.cmake:38 (include)
  /home/developer/workspaces/ros2-linux/share/rmw_connext_cpp/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /home/developer/workspaces/ros2-linux/share/rmw_connext_cpp/cmake/rmw_connext_cppConfig.cmake:38 (include)
  /home/developer/workspaces/ros2-linux/share/rmw_implementation_cmake/cmake/call_for_each_rmw_implementation.cmake:61 (find_package)
  cmake/rosidl_generator_py_get_typesupports.cmake:26 (call_for_each_rmw_implementation)
  CMakeLists.txt:61 (rosidl_generator_py_get_typesupports)


CMake Warning at /home/developer/workspaces/ros2-linux/share/rmw_connext_shared_cpp/cmake/ament_cmake_export_libraries-extras.cmake:62 (message):
  Package 'rmw_connext_shared_cpp' exports the library
  '/opt/rti.com/rti_connext_dds-5.3.1/lib/x64Linux3gcc5.4.0/libnddsc.so'
  which doesn't exist
Call Stack (most recent call first):
  /home/developer/workspaces/ros2-linux/share/rmw_connext_shared_cpp/cmake/rmw_connext_shared_cppConfig.cmake:38 (include)
  /home/developer/workspaces/ros2-linux/share/rmw_connext_cpp/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /home/developer/workspaces/ros2-linux/share/rmw_connext_cpp/cmake/rmw_connext_cppConfig.cmake:38 (include)
  /home/developer/workspaces/ros2-linux/share/rmw_implementation_cmake/cmake/call_for_each_rmw_implementation.cmake:61 (find_package)
  cmake/rosidl_generator_py_get_typesupports.cmake:26 (call_for_each_rmw_implementation)
  CMakeLists.txt:61 (rosidl_generator_py_get_typesupports)


CMake Warning at /home/developer/workspaces/ros2-linux/share/rmw_connext_shared_cpp/cmake/ament_cmake_export_libraries-extras.cmake:62 (message):
  Package 'rmw_connext_shared_cpp' exports the library
  '/opt/rti.com/rti_connext_dds-5.3.1/lib/x64Linux3gcc5.4.0/libnddscore.so'
  which doesn't exist
Call Stack (most recent call first):
  /home/developer/workspaces/ros2-linux/share/rmw_connext_shared_cpp/cmake/rmw_connext_shared_cppConfig.cmake:38 (include)
  /home/developer/workspaces/ros2-linux/share/rmw_connext_cpp/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /home/developer/workspaces/ros2-linux/share/rmw_connext_cpp/cmake/rmw_connext_cppConfig.cmake:38 (include)
  /home/developer/workspaces/ros2-linux/share/rmw_implementation_cmake/cmake/call_for_each_rmw_implementation.cmake:61 (find_package)
  cmake/rosidl_generator_py_get_typesupports.cmake:26 (call_for_each_rmw_implementation)
  CMakeLists.txt:61 (rosidl_generator_py_get_typesupports)


CMake Warning at /home/developer/workspaces/ros2-linux/share/rmw_connext_shared_cpp/cmake/ament_cmake_export_libraries-extras.cmake:62 (message):
  Package 'rmw_connext_shared_cpp' exports the library
  '/opt/rti.com/rti_connext_dds-5.3.1/lib/x64Linux3gcc5.4.0/libnddscpp.so'
  which doesn't exist
Call Stack (most recent call first):
  /home/developer/workspaces/ros2-linux/share/rmw_connext_shared_cpp/cmake/rmw_connext_shared_cppConfig.cmake:38 (include)
  /home/developer/workspaces/ros2-linux/share/rmw_connext_cpp/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /home/developer/workspaces/ros2-linux/share/rmw_connext_cpp/cmake/rmw_connext_cppConfig.cmake:38 (include)
  /home/developer/workspaces/ros2-linux/share/rmw_implementation_cmake/cmake/call_for_each_rmw_implementation.cmake:61 (find_package)
  cmake/rosidl_generator_py_get_typesupports.cmake:26 (call_for_each_rmw_implementation)
  CMakeLists.txt:61 (rosidl_generator_py_get_typesupports)


CMake Warning at /home/developer/workspaces/ros2-linux/share/rmw_connext_shared_cpp/cmake/ament_cmake_export_libraries-extras.cmake:62 (message):
  Package 'rmw_connext_shared_cpp' exports the library
  '/opt/rti.com/rti_connext_dds-5.3.1/lib/x64Linux3gcc5.4.0/librticonnextmsgcpp.so'
  which doesn't exist
Call Stack (most recent call first):
  /home/developer/workspaces/ros2-linux/share/rmw_connext_shared_cpp/cmake/rmw_connext_shared_cppConfig.cmake:38 (include)
  /home/developer/workspaces/ros2-linux/share/rmw_connext_cpp/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /home/developer/workspaces/ros2-linux/share/rmw_connext_cpp/cmake/rmw_connext_cppConfig.cmake:38 (include)
  /home/developer/workspaces/ros2-linux/share/rmw_implementation_cmake/cmake/call_for_each_rmw_implementation.cmake:61 (find_package)
  cmake/rosidl_generator_py_get_typesupports.cmake:26 (call_for_each_rmw_implementation)
  CMakeLists.txt:61 (rosidl_generator_py_get_typesupports)


CMake Warning at /home/developer/workspaces/ros2-linux/share/rmw_connext_shared_cpp/cmake/ament_cmake_export_libraries-extras.cmake:62 (message):
  Package 'rmw_connext_shared_cpp' exports the library
  '/opt/rti.com/rti_connext_dds-5.3.1/lib/x64Linux3gcc5.4.0/libnddscd.so'
  which doesn't exist
Call Stack (most recent call first):
  /home/developer/workspaces/ros2-linux/share/rmw_connext_shared_cpp/cmake/rmw_connext_shared_cppConfig.cmake:38 (include)
  /home/developer/workspaces/ros2-linux/share/rmw_connext_cpp/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /home/developer/workspaces/ros2-linux/share/rmw_connext_cpp/cmake/rmw_connext_cppConfig.cmake:38 (include)
  /home/developer/workspaces/ros2-linux/share/rmw_implementation_cmake/cmake/call_for_each_rmw_implementation.cmake:61 (find_package)
  cmake/rosidl_generator_py_get_typesupports.cmake:26 (call_for_each_rmw_implementation)
  CMakeLists.txt:61 (rosidl_generator_py_get_typesupports)


CMake Warning at /home/developer/workspaces/ros2-linux/share/rmw_connext_shared_cpp/cmake/ament_cmake_export_libraries-extras.cmake:62 (message):
  Package 'rmw_connext_shared_cpp' exports the library
  '/opt/rti.com/rti_connext_dds-5.3.1/lib/x64Linux3gcc5.4.0/libnddscored.so'
  which doesn't exist
Call Stack (most recent call first):
  /home/developer/workspaces/ros2-linux/share/rmw_connext_shared_cpp/cmake/rmw_connext_shared_cppConfig.cmake:38 (include)
  /home/developer/workspaces/ros2-linux/share/rmw_connext_cpp/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /home/developer/workspaces/ros2-linux/share/rmw_connext_cpp/cmake/rmw_connext_cppConfig.cmake:38 (include)
  /home/developer/workspaces/ros2-linux/share/rmw_implementation_cmake/cmake/call_for_each_rmw_implementation.cmake:61 (find_package)
  cmake/rosidl_generator_py_get_typesupports.cmake:26 (call_for_each_rmw_implementation)
  CMakeLists.txt:61 (rosidl_generator_py_get_typesupports)


CMake Warning at /home/developer/workspaces/ros2-linux/share/rmw_connext_shared_cpp/cmake/ament_cmake_export_libraries-extras.cmake:62 (message):
  Package 'rmw_connext_shared_cpp' exports the library
  '/opt/rti.com/rti_connext_dds-5.3.1/lib/x64Linux3gcc5.4.0/libnddscppd.so'
  which doesn't exist
Call Stack (most recent call first):
  /home/developer/workspaces/ros2-linux/share/rmw_connext_shared_cpp/cmake/rmw_connext_shared_cppConfig.cmake:38 (include)
  /home/developer/workspaces/ros2-linux/share/rmw_connext_cpp/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /home/developer/workspaces/ros2-linux/share/rmw_connext_cpp/cmake/rmw_connext_cppConfig.cmake:38 (include)
  /home/developer/workspaces/ros2-linux/share/rmw_implementation_cmake/cmake/call_for_each_rmw_implementation.cmake:61 (find_package)
  cmake/rosidl_generator_py_get_typesupports.cmake:26 (call_for_each_rmw_implementation)
  CMakeLists.txt:61 (rosidl_generator_py_get_typesupports)


CMake Warning at /home/developer/workspaces/ros2-linux/share/rmw_connext_shared_cpp/cmake/ament_cmake_export_libraries-extras.cmake:62 (message):
  Package 'rmw_connext_shared_cpp' exports the library
  '/opt/rti.com/rti_connext_dds-5.3.1/lib/x64Linux3gcc5.4.0/librticonnextmsgcppd.so'
  which doesn't exist
Call Stack (most recent call first):
  /home/developer/workspaces/ros2-linux/share/rmw_connext_shared_cpp/cmake/rmw_connext_shared_cppConfig.cmake:38 (include)
  /home/developer/workspaces/ros2-linux/share/rmw_connext_cpp/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /home/developer/workspaces/ros2-linux/share/rmw_connext_cpp/cmake/rmw_connext_cppConfig.cmake:38 (include)
  /home/developer/workspaces/ros2-linux/share/rmw_implementation_cmake/cmake/call_for_each_rmw_implementation.cmake:61 (find_package)
  cmake/rosidl_generator_py_get_typesupports.cmake:26 (call_for_each_rmw_implementation)
  CMakeLists.txt:61 (rosidl_generator_py_get_typesupports)
```
</details>

<details><summary>node name prefix to `__ns` works fine</summary>

```
$ ros2 run demo_nodes_cpp talker talker:__ns:=/new_ns
[INFO] [new_ns.talker]: Publishing: 'Hello World: 1'
```
</details>

<details><summary>Able to launch process with an environment variable, but could not kill the process using `CTRL` + `c`</summary>

Created launch file

```python
from launch import LaunchDescription
from launch import LaunchService
from launch.actions.execute_process import ExecuteProcess


def generate_launch_description():
    """Test launching a process with an environment variable."""
    ld = LaunchDescription([
        ExecuteProcess(
            cmd=['env'], output='screen',
            env={'TEST_PROCESS_WITH_ENV': 'Hello World'},
        )
    ])
    return ld
```

Ran successfully, but I could not kill the process using `CTRL` + `c` or sigint directly.

```
$ ros2 launch src/test_pkg/test_env.launch.py 
[INFO] [launch]: process[env-1]: started with pid [4212]
[INFO] [launch]: process[env-1]: process has finished cleanly
TEST_PROCESS_WITH_ENV=Hello World

^C


^C
^C
^C
```

In another terminal

```
# Sent sigint, no response
subshell$ kill -SIGINT 4203

# Sent sigterm, this killed the process but process printed `KeyboardInterrupt` after receiving it?
subshell$ kill -SIGTERM 4203
```

Weirdly, after sending sigterm (not sigint or `ctrl` + `c`) the launch process output

```
Exception ignored in: <module 'threading' from '/usr/lib/python3.5/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 1288, in _shutdown
    t.join()
  File "/usr/lib/python3.5/threading.py", line 1054, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.5/threading.py", line 1070, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
  File "/home/developer/workspaces/ros2-linux/lib/python3.5/site-packages/launch/utilities/signal_management.py", line 120, in __on_sigint
    __original_sigint_handler(signum, frame)
KeyboardInterrupt
```

</details>


<details><summary>ros2cli without rmw_fastrtps_cpp gives a friendly warning</summary>

```
subshell$ mv lib/librmw_fastrtps_cpp.so lib/librmw_fastrtps_cpp.so.bak
subshell$ ros2 daemon stop
The daemon has been stopped
subshell$ ros2 node list
Unable to get rmw_implementation_identifier, try specifying the implementation to use via the 'RMW_IMPLEMENTATION' environment variable
```
</details>

<details><summary>Pluginlib appears to be exporting the rcutils dependency correctly</summary>

I created a dummy package that found `pluginlib` and checked to see that `rcutils` was found too.

```cmake
cmake_minimum_required(VERSION 3.5)
project(test_pkg)

# Default to C++14
if(NOT CMAKE_CXX_STANDARD)
  set(CMAKE_CXX_STANDARD 14)
endif()

if(NOT WIN32)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Wextra -Wpedantic")
endif()

find_package(ament_cmake REQUIRED)
find_package(pluginlib REQUIRED)

if (rcutils_FOUND)
  message(STATUS "rcutils was found by plugin lib")
else()
  message(STATUS "rcutils was not found by plugin lib")
endif()

ament_package()
```

```xml
<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format2.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="2">
  <name>test_pkg</name>
  <version>0.5.1</version>
  <description>test package</description>

  <maintainer email="noone@osrfoundation.org">No one</maintainer>
  <license>Apache License 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_depend>pluginlib</build_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>

```

Then built the package

```
subshell$ colcon build --event-handlers console_direct+ --packages-select test_pkg
Starting >>> test_pkg
-- Found ament_cmake: 0.5.1 (/home/developer/workspaces/ros2-linux/share/ament_cmake/cmake)
-- Using PYTHON_EXECUTABLE: /usr/bin/python3
-- Found pluginlib: 2.1.1 (/home/developer/workspaces/ros2-linux/share/pluginlib/cmake)
-- Found poco_vendor:  (/home/developer/workspaces/ros2-linux/share/poco_vendor/cmake)
-- rcutils was found by plugin lib
```

</details>

**Comment by mikaelarguedas** [comment]
> Python publisher slowly leaks, python subscriber does not leak

This should not leak at all like on master.
@dirk-thomas you tested that on bionic, do you see the same behavior?

> Building rosidl_generator_py has a lot of cmake warnings, but passes

expected (if you don't have connext installed) :+1:

> Able to launch process with an environment variable, but could not kill the process using `CTRL` + `c`

Expected? @wjwwood to confirm

**Comment by sloretz** [comment]
> This should not leak at all like on master.

Roger. For what it's worth it leaks a lot less with the patch release than the initial release

initial release: 32956 KiB at CPU time 0.91 seconds, 66484 KiB at 1min 2.94 seconds CPU time
patch1: 28840 KiB at CPU time 1.63 seconds, 36496 KiB at 1 min 1.54 seconds CPU time

The launch `CTRL` + `c` behavior seems to be the same on both patched an unpatched. Repeating the test on both (minus the `env` keyword argument) I can't kill either using sigint, and sigterm only randomly works. I'm not sure what's going on but the patch release doesn't make it worse.

**Comment by mikaelarguedas** [comment]
Thanks @sloretz for the testing!

Regarding the Python leak:

As this example doesn't follow hour guidelines (never spins or let the time to the underlying machinery to run) I am not sure this is a good testing setup.

I tested this on Xenial using a 1kHz publish loop and let it run for 10minutes (621k messages) without noticing a single byte increase on either side. So I'm going to say it's good enough (/much better) for the patch release.

<details>
<summary>Terminal1</summary>

```
$ ros2 topic pub /chatter geometry_msgs/Twist -r 1000 -p 1000
```

</details>

<details>
<summary>Terminal2</summary>

```
$ ros2 topic echo /chatter > /dev/null
```

</details>

Though it may be good to test it at higher frequencies and/or for bigger messages to see where the breaking point is.

**Comment by wjwwood** [comment]
Ctrl c of launch is still expected to be broken.

**Comment by dhood** [comment]
OS X binary spot check looks fine (though I found I had to reinstall my python dependencies after upgrading to python3.7). Building an overlay without e.g. opensplice using colcon works ok. I couldn't upgrade to qt11 on osx 10.10 (not supported) so wasn't able to test rviz, but `DYLD_LIBRARY_PATH` gets extended to include ogre libs correctly in zsh.

**Comment by dirk-thomas** [comment]
> This should not leak at all like on master.
> you tested that on bionic, do you see the same behavior?

I tried (again) with the setup mentioned in the original ticket (`ros2 topic pub /topic <nested msg e.g. geometry_msgs/Vector2Stamped> -r 1000 -p 1000`, `ros2 topic echo /topic`) and it doesn't leak any memory.

> For what it's worth it leaks a lot less with the patch release than the initial release

With the custom Python code I do see an increasing memory usage. It might be due to the fact that the custom code runs a busy loop - adding a `sleep(0.001)` after each publish give the GC a "chance" to run. With that change I don't see any leak.

**Comment by sloretz** [comment]
> With the custom Python code I do see an increasing memory usage. It might be due to the fact that the custom code runs a busy loop - adding a sleep(0.001) after each publish give the GC a "chance" to run. With that change I don't see any leak.

Adding a direct call to `gc.collect()` makes the memory usage constant too.

**Comment by mikaelarguedas** [comment]
Path release is out https://discourse.ros.org/t/new-packages-for-ros-2-bouncy-2018-07-20/5421

closing
