### ISSUE TITLE
Bouncy Patch release 3

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/ros2#575]
Ticket to aggregate the list of tickets that should be fixed and / or backported

## Tickets to address:

- [ ] `<Link to ticket>`

## PRs to backport
- [ ] `<PR link>`: Backported PR link: `<link>`
- [x] ros2/geometry2/pull/86 Allow static_transform_publisher to be run with ros arguments
- [ ] ros2/rclpy#288 Fix crash in rclpy on SIGINT
- [ ]  ros2/rclcpp#656 Fix memory leak in rclcpp wait_for_service

## Repositories to release

- [ ] `<link to repository>`: `<link to rosdistro PR>`
- [ ] https://github.com/ros2/geometry2 (for https://github.com/ros2/geometry2/pull/86): N/A

## Rerun bloom

This is for repositories that we don't tag but need to perform a new release of.

@nuclearsandwich FYI

**Comment by sloretz** [comment]
PRs to backport

- [ ] ros2/rclpy#288 Fix crash in rclpy on SIGINT
- [ ] ros2/rclcpp#656 Fix memory leak in rclcpp wait_for_service

**Comment by clalancette** [comment]
Bouncy is no longer supported (it went out of support in July 2019).  Therefore there will be no patch release 3, so I'll close this out.
