### ISSUE TITLE
[ROS2 QA meta-ticket] Automatically Surface ROS 2 Reliability Issues

### ISSUE THREAD

**Issue by thomas-moulard** [ros2/ros2#662]
As a ROS 2 developer, I have access to a report detailing potential regressions in the ROS 2 communication layer such as memory or concurrency related bugs. This report must be updated on
a regular basis (e.g. nightly) and should cover all ROS 2 communication packages (`rmw*` / `rcl*`).

Low-hanging fruits to close the gap between Linux, Mac OS X and Windows builds should be tackled. This will organically prevent regressions on Mac and Windows platform while improving developer productivity.

Owner: @ros2/aws-robotics

# Exit Criteria

- The scripts and tools required to generate the report automatically are built and reviewed.
- The scripts are deployed and the report is generated automatically.
- The new system is adopted by the community. Reviewers monitor regressions and make rollback decisions based on the system output.

# Tasks

- [x] Add ASan sanitizer nightly job to ROS2 CI https://github.com/ros2/ros2/issues/665
- [x] Add TSan sanitizer nightly job to ROS2 CI https://github.com/ros2/ros2/issues/666
- [x] [Add a CI job for Clang Linux nightly builds](https://discourse.ros.org/t/ci-ros2-org-clang-nightly-job-now-available/7857)
- [x] Implement PoC for Thread-Safety annotation https://github.com/ros2/ros2/issues/664
