### ISSUE TITLE
Crystal Patch Release 4

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/ros2#668]
This issue will track the list of changes that should be included in the next Crystal patch release. The date for this patch release is scheduled for 2019-04-04 and will be determined by a critical mass of desired changes ready to be released.

---

#### Changes proposed for backport this patch release

- [x] https://github.com/ros2/launch/pull/223 ~~ros2/launch#221~~ (cherry-pick of ros2/launch#169)
- [x] https://github.com/ros2/launch/pull/222 ~~ros2/launch#220~~ (partial cherry-pick of ros2/launch#167)
- [x] ros2/rclcpp#686
      - Backports ros2/rclcpp#637 - fixes ros2/rclcpp#683
- [x] ros2/rclpy#288 - fixes crash on SIGINT in rclpy
- [x] Backported by ros2/rmw_fastrtps#268:
  - [x] ros2/rmw_fastrtps#264 - fixes race condition in rmw_fastrtps 
  - [x] ros2/rmw_fastrtps#256 - compile fix needed to switch to Fast-RTPS v1.7.2
- [x] Update to Fast-RTPS v1.7.2

#### Changes in progress for this release

---

All pull requests included in this release. Organized by repository and backport PR.

<details><summary>eProsima/Fast-RTPS</summary>
The changes in Fast-RTPS are discussed in <a href="https://github.com/ros2/ros2/issues/669">ros2/ros2#669</a>.<br>
For a complete summary of changes see: <a href="https://github.com/eProsima/Fast-RTPS/compare/b48ce9d2fba6fc94e756da01c58b72f2ad848238...v1.7.2">b48ce9d...v1.7.2</a>.
</details>

<details><summary>ros2/launch</summary>
<ul>
<li><a href="https://github.com/ros2/launch/pull/223">ros2/launch#223</a>
	<ul>
	<li><a href="https://github.com/ros2/launch/pull/169">ros2/launch#169</a></li>
	</ul>
</li>
<li><a href="https://github.com/ros2/launch/pull/222">ros2/launch#222</a>
	<ul>
		<li><a href="https://github.com/ros2/launch/pull/167">ros2/launch#167</a>(partial)</li>
	</ul>
</li>
</ul>
</details>

<details><summary>ros2/rclcpp</summary>
<ul>
<li><a href="https://github.com/ros2/rclcpp/pull/686">ros2/rclcpp#686</a>
	<ul>
	<li><a href="https://github.com/ros2/rclcpp/pull/637">ros2/rclcpp#637</a></li>
	</ul>
</li>
</ul>
</details>

<details><summary>ros2/rclpy</summary>
<ul>
<li><a href="https://github.com/ros2/rclpy/pull/298">ros2/rclpy#298</a>
	<ul>
	<li><a href="https://github.com/ros2/rclpy/pull/288">ros2/rclpy#288</a></li>
	</ul>
</li>
</ul>
</details>

<details><summary>ros2/rmw_fastrtps</summary>
<ul>
<li><a href="https://github.com/ros2/rmw_fastrtps/pull/235">ros2/rmw_fastrtps#235</a></li>
<li><a href="https://github.com/ros2/rmw_fastrtps/pull/245">ros2/rmw_fastrtps#245</a></li>
<li><a href="https://github.com/ros2/rmw_fastrtps/pull/248">ros2/rmw_fastrtps#248</a></li>
<li><a href="https://github.com/ros2/rmw_fastrtps/pull/247">ros2/rmw_fastrtps#247</a></li>
<li><a href="https://github.com/ros2/rmw_fastrtps/pull/250">ros2/rmw_fastrtps#250</a></li>
<li><a href="https://github.com/ros2/rmw_fastrtps/pull/238">ros2/rmw_fastrtps#238</a></li>
<li><a href="https://github.com/ros2/rmw_fastrtps/pull/254">ros2/rmw_fastrtps#254</a></li>
<li><a href="https://github.com/ros2/rmw_fastrtps/pull/268">ros2/rmw_fastrtps#268</a>
	<ul>
	<li><a href="https://github.com/ros2/rmw_fastrtps/pull/256">ros2/rmw_fastrtps#256</a></li>
	<li><a href="https://github.com/ros2/rmw_fastrtps/pull/264">ros2/rmw_fastrtps#264</a></li>
	</ul>
</li>
</ul>
</details>

**Comment by nuclearsandwich** [comment]
As [mentioned previously](https://github.com/ros2/ros2/issues/656#issuecomment-473076708) and discussed internally, (calling @clalancette as the current leader of that discussion), we should consider updating the version of Fast-RTPS in Crystal to resolve ros2/rmw_fastrtps#257 and ros2/rmw_fastrtps#258.

**Comment by clalancette** [comment]
I'm now tracking the Fast-RTPS issue at https://github.com/ros2/ros2/issues/669; I'll put further notes in there while we figure out what to do for Crystal patch release 4.

**Comment by wjwwood** [comment]
Can we add a partial cherry-pick on the launch repository?

https://github.com/ros2/launch/commit/632ef1f3eca7dbc54fbed85ab65a5efc512d83ed#diff-970fc3c5d394ad33c14e4f9fe55288ceR113

Via

- https://github.com/ros2/launch/pull/220
- https://github.com/ros2/launch/pull/167#issuecomment-476960691

**Comment by wjwwood** [comment]
@stonier FYI

**Comment by nuclearsandwich** [comment]
A possible regression in rclcpp_action, which wasn't released this round and thus why it wasn't caught during the backport process, has been found https://github.com/ros2/rclcpp/issues/683.

**Comment by nuclearsandwich** [comment]
Full CI with a fix for ros2/rclcpp#683. If this comes back with no unexpected failures we'll re-release rclcpp and include it in this patch release.

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=6633)](http://ci.ros2.org/job/ci_linux/6633/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=2959)](http://ci.ros2.org/job/ci_linux-aarch64/2959/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=5443)](http://ci.ros2.org/job/ci_osx/5443/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=6456)](http://ci.ros2.org/job/ci_windows/6456/)

**Comment by nuclearsandwich** [comment]
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=6638)](http://ci.ros2.org/job/ci_linux/6638/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=2964)](http://ci.ros2.org/job/ci_linux-aarch64/2964/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=5448)](http://ci.ros2.org/job/ci_osx/5448/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=6461)](http://ci.ros2.org/job/ci_windows/6461/)

**Comment by nuclearsandwich** [comment]
Packaging jobs

* Linux Bionic [![Build Status](https://ci.ros2.org/buildStatus/icon?job=packaging_linux&build=1426)](https://ci.ros2.org/job/packaging_linux/1426/)
* Linux Xenial [![Build Status](https://ci.ros2.org/buildStatus/icon?job=packaging_linux&build=1427)](https://ci.ros2.org/job/packaging_linux/1427/)
* Linux Bionic (ARM64) [![Build Status](https://ci.ros2.org/buildStatus/icon?job=packaging_linux-aarch64&build=772)](https://ci.ros2.org/job/packaging_linux-aarch64/772/)
* Linux Xenial (ARM64) [![Build Status](https://ci.ros2.org/buildStatus/icon?job=packaging_linux-aarch64&build=773)](https://ci.ros2.org/job/packaging_linux-aarch64/773/)
* macOS [![Build Status](https://ci.ros2.org/buildStatus/icon?job=packaging_osx&build=1428)](https://ci.ros2.org/job/packaging_osx/1428/)
* Windows [![Build Status](https://ci.ros2.org/buildStatus/icon?job=packaging_windows&build=1335)](https://ci.ros2.org/job/packaging_windows/1335/)
* Windows Debug [![Build Status](https://ci.ros2.org/buildStatus/icon?job=packaging_windows_debug&build=285)](https://ci.ros2.org/job/packaging_windows_debug/285/)

**Comment by nuclearsandwich** [comment]
I keep forgetting that PRs to the `crystal` branch won't auto-close issues.
