### ISSUE TITLE
switch to Connext 5.2

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/ros2#70]
* [x] depends on the source being available to us
* [x] create new Debian package
* [ ] create VS 2015 package to fix runtime problem of prebuilt packages: ros2/ros2#51
  * [x] some of the tests already pass with Connext 5.2 Pro (which is built with VS 2013), hopefully the custom built will make all pass...
* [x] ~~either build from source for OS X or~~ test prebuilt binary packages on OS X
* [x] update rmw_connext repo: ros2/rmw_connext#75 ros2/rmw_connext#54
* [x] update tests to cover unbounded string and sequences: ros2/system_tests#17
* [x] update CI scripts #75

**Comment by esteve** [comment]
Preliminary Debian packaging in:

https://github.com/rticommunity/rticonnextdds-src/pull/8

Debian packages in:

https://github.com/osrf/rticonnextdds-src/tree/binaries/ubuntu/trusty/amd64/5.2.0-0

**Comment by dirk-thomas** [comment]
PR to update the Docker image: ros2/ros2#75

**Comment by esteve** [comment]
Final Debian packaging already merged into upstream RTI repo:

https://github.com/rticommunity/rticonnextdds-src/commit/13830c921718cdbef801179d14ba8b53cc83a18a

Debian packages in:

https://github.com/osrf/rticonnextdds-src/tree/binaries/ubuntu/trusty/amd64/5.2.0-1

CI scripts:

https://github.com/ros2/ros2/pull/75

**Comment by dirk-thomas** [comment]
I am closing this since the only remaining task is the custom Connext package built with Visual Studio 2015 which is tracked in a separate ticket.
