### ISSUE TITLE
Per-node output logging meta-ticket

### ISSUE THREAD

**Issue by clalancette** [ros2/ros2#789]
This is a meta-ticket for tracking the pieces that need to go into Eloquent to get per-node logging working.  Essentially, this feature ensures that stdout and stderr output from a node is logged even if it is run via `ros2 run`.  It also separately gets logged if it is launched via `ros2 launch`, but that is out of scope for this ticket.

Here are the pieces necessary:
- [x] Vendor the spdlog library: https://github.com/clalancette/spdlog_vendor
  - [x] Move into the ros2 organization
  - [x] Open a PR against https://github.com/ros2/ros2/blob/master/ros2.repos to add it: https://github.com/ros2/ros2/pull/790
  - [x] Release spdlog_vendor into Eloquent: https://github.com/ros/rosdistro/pull/22523
- [x] Add mkdir to rcutils: https://github.com/ros2/rcutils/pull/166
- [x] Add rcl_logging_spdlog backend to rcl_logging: https://github.com/ros2/rcl_logging/pull/17
- [x] Change the default logger to the new backend: https://github.com/ros2/rcl/pull/466
- [x] Release updated rcl into Eloquent: https://github.com/ros/rosdistro/pull/22595

**Comment by clalancette** [comment]
CI for this whole thing:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=8235)](http://ci.ros2.org/job/ci_linux/8235/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=4204)](http://ci.ros2.org/job/ci_linux-aarch64/4204/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=6713)](http://ci.ros2.org/job/ci_osx/6713/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=8118)](http://ci.ros2.org/job/ci_windows/8118/)

**Comment by clalancette** [comment]
All right, I now fixed the bug that was causing previous test failures.  All of the failures in here are also in the nightlies, so @ros2/team this should be ready for review.

**Comment by clalancette** [comment]
Another CI, given that there have been a bunch of changes here:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=8261)](http://ci.ros2.org/job/ci_linux/8261/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=4221)](http://ci.ros2.org/job/ci_linux-aarch64/4221/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=6736)](http://ci.ros2.org/job/ci_osx/6736/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=8148)](http://ci.ros2.org/job/ci_windows/8148/)

**Comment by clalancette** [comment]
All pieces merged and released into Eloquent :tada: .  Closing this meta-ticket out.
