### ISSUE TITLE
Rolling rosdistro meta-ticket

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/ros2#843]
This issue will track the work needed to bring a rolling ROS 2 distribution to life.

- REP
  - [x] Draft REP-2002 (https://github.com/ros-infrastructure/rep/pull/209)
  - [ ] Iterate based on feedback and prototype implementation experience (ongoing)
  - [ ] Merge REP-2002
- Prototype and implementation
  - [x] Create a test environment for prototyping
    - sample rosdistro https://github.com/nuclearsandwich-ros/rosdistro
    - sample ros_buildfarm_config https://github.com/nuclearsandwich-ros/ros_buildfarm_config
  - Prototype tools for rolling rosdistro requirements
    - [ ] tool to create a new rosdistro from an existing base distro ([requirement in REP-2002](https://github.com/nuclearsandwich/rep/blob/rep-2002/rep-2002.rst#releasing-stable-ros-distributions-from-a-rolling-release))
    - [ ] tool to include packages in a rosdistro when dependencies are available. ([requirement in REP-2002](https://github.com/nuclearsandwich/rep/blob/rep-2002/rep-2002.rst#releasing-stable-ros-distributions-from-a-rolling-release) (2nd half))
    - [ ] tool to update rosdistro packages for a new platform ([requirement in REP-2002](https://github.com/nuclearsandwich/rep/blob/rep-2002/rep-2002.rst#bootstrapping-the-rolling-release)) 
- Integration and deployment
  - [ ] Integrate tools into ros_buildfarm, bloom, superflore and/or a new project
  - [ ] Deploy updated tools to the buildfarm
  - [ ] Bootstrap the first rolling release

**Comment by nuclearsandwich** [comment]
There's now a repository https://github.com/nuclearsandwich/rosnroll which contains a script and instructions for running a couple demos that use it.

[One demo](https://github.com/nuclearsandwich/rosnroll/tree/latest/new-rosdistro) copies an eloquent release into a new "verystable" distribution, as we would use the production version of this tool to create a new stable distribution from an existing rolling distribution and [a second](https://github.com/nuclearsandwich/rosnroll/tree/latest/update-platform) updates the platform of our sample eloquent distribution from bionic to focal.

Instructions for running the demo scripts are in the repository's [README](https://github.com/nuclearsandwich/rosnroll/blob/latest/README.md).

Since the script currently takes all repositories and just drops the release version if bloom is unsuccessful, we're much closer to having a script which can retry failed packages but I haven't set up the demo/test data to verify it yet.

Next week I'll take some time to discuss changes we could make in bloom to facilitate better patching and non-interactive use with other bloom contributors and move on to setting up the retrying demo.

**Comment by nuclearsandwich** [comment]
A [third demo](https://github.com/nuclearsandwich/rosnroll/tree/latest/update-rosdistro) has been added to https://github.com/nuclearsandwich/rosnroll which demos retrying previously unreleased repositories in an already created rosdistro.
