### ISSUE TITLE
Topic Statistics Meta Ticket

### ISSUE THREAD

**Issue by dabonnie** [ros2/ros2#901]
This issue will track the work needed to complete ROS2 Topic Statistics.

## Dependencies

 - [x] Define statistics message in `rcl_interfaces' (https://github.com/ros2/rcl_interfaces/pull/98)
 - [x] Move `libstatistics_collector` to separate repository (https://github.com/ros-tooling/libstatistics_collector/pull/2)
 - [x] Add `libstatistics_collector` to `ros2.repos` file (https://github.com/ros2/ros2/pull/897)
 - [x] Fix 'libstatistics_collector' Windows issues (https://github.com/ros-tooling/system_metrics_collector/pull/137)

## Integration with `rclcpp`

 - [x] Define Topic Statistics classes in `rclcpp` (https://github.com/ros2/rclcpp/pull/1050)
 - [x] Integrate TopicStatistics classes in subscriber `handle_message` (https://github.com/ros2/rclcpp/pull/1072)
 - [x] Add SubscriptionOptions for Topic Statistics (https://github.com/ros2/rclcpp/pull/1057)
 - [x] Add NodeDefault option for enabling topic statistics (https://github.com/ros2/rclcpp/pull/1074)
 - [x] Add received message age measurement to Topic Statistics (https://github.com/ros2/rclcpp/pull/1080)

**Comment by dabonnie** [comment]
This is now complete given ros2/rclcpp#1080's merge.

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-foxy-fitzroy-released/14495/1
