### ISSUE TITLE
TinyXML2 Migration Tracking Issue

### ISSUE THREAD

**Issue by mjcarroll** [ros2/ros2#987]
This issue is to track the task of migrating all usage of `TinyXML` to `TinyXML2` in the ROS2 core codebase.

An inspection with `colcon graph` shows that these packages still directly depend on `tinyxml_vendor`:

- [x] urdfdom https://github.com/ros2/urdfdom/pull/17
- [x] urdf https://github.com/ros2/urdf/pull/17
- [x] kdl_parser https://github.com/ros/kdl_parser/43

All of the ones below have recursive dependencies on tinyxml_vendor, so they will automatically go away when the above are fixed:

* robot_state_publisher
* dummy_robot_bringup
* rviz_common
* rviz_visual_testing_framework
* rviz_default_plugins
* rviz2
