### ISSUE TITLE
QNX Support

### ISSUE THREAD

**Issue by asobhy-qnx** [ros2/ros2#988]
This issue will track patches related to building ROS2 for QNX 7.1 real-time operating system.

The patches will allow users to cross-compile ROS2 for the supported architectures below.

**QNX supported architectures as of version 7.1:**
- x86_64
- armv8 (aarch64)
- armv7

**A brief summary of the steps needed to cross compile ROS2 for QNX:** 
_Notes: 
-More detailed instructions will be provided when project is done. These steps are for who do not want to wait
-The issues checklist below represent the changes that you will need to make sure you have when you checkout the source code. Some patches have not been merged yet so you might want to manually apply the patches_

1. After checking out ROS2 source code following the normal steps, checkout https://github.com/asobhy-qnx/ros2 which contains the toolchain file and a convenience build.sh script. The files need to be placed inside ros2 parent directory.
2. cross compile the dependencies below and place them in a staging directory so you can build against them.
3. set the QNX_STAGE variable inside the qnxsdp-env.sh script to the path of your staging directory above and add it to the list of QNX environment exported variables.
4. source qnxsdp-env.sh
5. run build.sh
6. when done files inside the staging dir and ros install dir will need to be copied to your target. 

**Extra dependencies that needs to be cross compiled before building ROS2:**
Dashing, Foxy. Rolling
- apr
- apr-util
- log4cxx
- asio
- eigen3
- libpng16
- opencv
- numpy
- lxml
- tinyxml2

Foxy, Rolling
- netifaces
- libbullet-dev

Since QNX will naturally be running on resource constrained embedded devices, it does not make sense to run visualization packages on them. This is why we will not support any of the ROS visualization packages for QNX at the moment. Users can easily visualize data published from QNX targets on their pcs instead, since communication across ROS nodes is OS-agnostic.

Issues checklist:

- [x] https://github.com/osrf/osrf_testing_tools_cpp/issues/51

- [x] https://github.com/google/benchmark/issues/1010 --> UPDATE VENDOR PACKAGE NEEDED https://github.com/ament/google_benchmark_vendor/issues/7 --> PR created

- [x] https://github.com/uncrustify/uncrustify/issues/2876 <-- UPDATE VENDOR PACKAGE NEEDED https://github.com/ament/uncrustify_vendor/issues/11

- [x] https://github.com/eProsima/Fast-DDS/issues/1309

- [x] https://github.com/eProsima/Fast-DDS/issues/1308

- [x] https://github.com/foonathan/memory/issues/84 <-- UPDATE VENDOR PACKAGE NEEDED https://github.com/eProsima/foonathan_memory_vendor/issues/37

- [x] https://github.com/ros2/rcutils/issues/281

- [x] https://github.com/ros2/realtime_support/tree/master/rttest --> getrusage RUSAGE_THREAD not implemented RUSAGE_SELF only --> COLCON_IGNOREd at the moment

- [x] pendulum control --> depends on rttest --> COLCON_IGNOREd at the moment

- [x] https://github.com/ros2/mimick_vendor -->  https://github.com/ros2/Mimick --> Not supported. CONCON_IGNOREd

- [x] rviz --> COLCON_IGNORE ( no visualization support at the moment )

- [x] ros-visualization --> COLCON_IGNORE ( no visualization support at the moment )

- [x] turtlesim --> COLCON_IGNORE ( no visualization support at the moment )

- [x] https://github.com/ros/pluginlib/issues/204

- [x] https://github.com/ros2/rcutils/issues/286

Extra Dashing patches:

- [x] https://github.com/ros/console_bridge/pull/88

- [x] https://github.com/ros2/poco_vendor/issues/27

- [x] https://github.com/ros2/tinyxml_vendor/issues/19  <--- Will add to list of qnx source dependencies

- [x] https://github.com/ros-perception/laser_geometry/issues/64

**Comment by asobhy-qnx** [comment]
is there a way to control the value for COLCON_CURRENT_PREFIX that will be placed in the setup and local setup scripts?

Currently I am patching the scripts with the value of the new path on target after the build is done, but I was thinking that there might be a variable I could set before building that could influence the value placed in the env sourcing scripts.

I already set the value TARGET_INSTALL_DIR but it has no effect on the value being placed inside those scripts.

**Comment by asobhy-qnx** [comment]
For bullet dependency are python bindings required?

**Comment by iluetkeb** [comment]
I'm curious why you're not using CMAKE_SYSROOT? It should address some of things automatically, particularly the rpath modifications.

**Comment by asobhy-qnx** [comment]
CMAKE_SYSROOT expects a sysroot filesystem tree for a single architecture. Since QNX supports multiple archs our sysroot does not contain the usr/include directory since it is common between the three architectures.

**Comment by iluetkeb** [comment]
Ah, interesting to hear. Personally, it would seem easier to me to copy over the /usr/include than to fiddle with rpaths, but that's your choice, of course :-)

**Comment by asobhy-qnx** [comment]
doing that will break a lot of other qnx stuff that is based on this filesystem tree and will take a lot more work to change. Adding an rpath-link option only provides the location of the libraries during link time. All of the cross-compiled libraries are built without an embedded rpath.

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-agenda-2020-09-17/16464/1

**Comment by clalancette** [comment]
@asobhy-qnx What's the status of this ticket?  Is there additional work that needs to be done here, or can we close this out?

**Comment by tongtongdi** [comment]
Does ros2 support qnx7.0?
